
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TempVoiceChannel` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TempVoiceChannel
 * 
 */
export type TempVoiceChannelModel = runtime.Types.Result.DefaultSelection<Prisma.$TempVoiceChannelPayload>

export type AggregateTempVoiceChannel = {
  _count: TempVoiceChannelCountAggregateOutputType | null
  _min: TempVoiceChannelMinAggregateOutputType | null
  _max: TempVoiceChannelMaxAggregateOutputType | null
}

export type TempVoiceChannelMinAggregateOutputType = {
  id: string | null
  systemId: string | null
  channelId: string | null
  ownerId: string | null
  templateType: $Enums.TempVoiceType | null
  createdAt: Date | null
  lastActiveAt: Date | null
}

export type TempVoiceChannelMaxAggregateOutputType = {
  id: string | null
  systemId: string | null
  channelId: string | null
  ownerId: string | null
  templateType: $Enums.TempVoiceType | null
  createdAt: Date | null
  lastActiveAt: Date | null
}

export type TempVoiceChannelCountAggregateOutputType = {
  id: number
  systemId: number
  channelId: number
  ownerId: number
  templateType: number
  createdAt: number
  lastActiveAt: number
  _all: number
}


export type TempVoiceChannelMinAggregateInputType = {
  id?: true
  systemId?: true
  channelId?: true
  ownerId?: true
  templateType?: true
  createdAt?: true
  lastActiveAt?: true
}

export type TempVoiceChannelMaxAggregateInputType = {
  id?: true
  systemId?: true
  channelId?: true
  ownerId?: true
  templateType?: true
  createdAt?: true
  lastActiveAt?: true
}

export type TempVoiceChannelCountAggregateInputType = {
  id?: true
  systemId?: true
  channelId?: true
  ownerId?: true
  templateType?: true
  createdAt?: true
  lastActiveAt?: true
  _all?: true
}

export type TempVoiceChannelAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TempVoiceChannel to aggregate.
   */
  where?: Prisma.TempVoiceChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceChannels to fetch.
   */
  orderBy?: Prisma.TempVoiceChannelOrderByWithRelationInput | Prisma.TempVoiceChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TempVoiceChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TempVoiceChannels
  **/
  _count?: true | TempVoiceChannelCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TempVoiceChannelMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TempVoiceChannelMaxAggregateInputType
}

export type GetTempVoiceChannelAggregateType<T extends TempVoiceChannelAggregateArgs> = {
      [P in keyof T & keyof AggregateTempVoiceChannel]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTempVoiceChannel[P]>
    : Prisma.GetScalarType<T[P], AggregateTempVoiceChannel[P]>
}




export type TempVoiceChannelGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TempVoiceChannelWhereInput
  orderBy?: Prisma.TempVoiceChannelOrderByWithAggregationInput | Prisma.TempVoiceChannelOrderByWithAggregationInput[]
  by: Prisma.TempVoiceChannelScalarFieldEnum[] | Prisma.TempVoiceChannelScalarFieldEnum
  having?: Prisma.TempVoiceChannelScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TempVoiceChannelCountAggregateInputType | true
  _min?: TempVoiceChannelMinAggregateInputType
  _max?: TempVoiceChannelMaxAggregateInputType
}

export type TempVoiceChannelGroupByOutputType = {
  id: string
  systemId: string
  channelId: string
  ownerId: string
  templateType: $Enums.TempVoiceType
  createdAt: Date
  lastActiveAt: Date
  _count: TempVoiceChannelCountAggregateOutputType | null
  _min: TempVoiceChannelMinAggregateOutputType | null
  _max: TempVoiceChannelMaxAggregateOutputType | null
}

type GetTempVoiceChannelGroupByPayload<T extends TempVoiceChannelGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TempVoiceChannelGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TempVoiceChannelGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TempVoiceChannelGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TempVoiceChannelGroupByOutputType[P]>
      }
    >
  >



export type TempVoiceChannelWhereInput = {
  AND?: Prisma.TempVoiceChannelWhereInput | Prisma.TempVoiceChannelWhereInput[]
  OR?: Prisma.TempVoiceChannelWhereInput[]
  NOT?: Prisma.TempVoiceChannelWhereInput | Prisma.TempVoiceChannelWhereInput[]
  id?: Prisma.StringFilter<"TempVoiceChannel"> | string
  systemId?: Prisma.StringFilter<"TempVoiceChannel"> | string
  channelId?: Prisma.StringFilter<"TempVoiceChannel"> | string
  ownerId?: Prisma.StringFilter<"TempVoiceChannel"> | string
  templateType?: Prisma.EnumTempVoiceTypeFilter<"TempVoiceChannel"> | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFilter<"TempVoiceChannel"> | Date | string
  lastActiveAt?: Prisma.DateTimeFilter<"TempVoiceChannel"> | Date | string
  system?: Prisma.XOR<Prisma.TempVoiceSystemScalarRelationFilter, Prisma.TempVoiceSystemWhereInput>
}

export type TempVoiceChannelOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  systemId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  templateType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  lastActiveAt?: Prisma.SortOrder
  system?: Prisma.TempVoiceSystemOrderByWithRelationInput
}

export type TempVoiceChannelWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  channelId?: string
  AND?: Prisma.TempVoiceChannelWhereInput | Prisma.TempVoiceChannelWhereInput[]
  OR?: Prisma.TempVoiceChannelWhereInput[]
  NOT?: Prisma.TempVoiceChannelWhereInput | Prisma.TempVoiceChannelWhereInput[]
  systemId?: Prisma.StringFilter<"TempVoiceChannel"> | string
  ownerId?: Prisma.StringFilter<"TempVoiceChannel"> | string
  templateType?: Prisma.EnumTempVoiceTypeFilter<"TempVoiceChannel"> | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFilter<"TempVoiceChannel"> | Date | string
  lastActiveAt?: Prisma.DateTimeFilter<"TempVoiceChannel"> | Date | string
  system?: Prisma.XOR<Prisma.TempVoiceSystemScalarRelationFilter, Prisma.TempVoiceSystemWhereInput>
}, "id" | "channelId">

export type TempVoiceChannelOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  systemId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  templateType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  lastActiveAt?: Prisma.SortOrder
  _count?: Prisma.TempVoiceChannelCountOrderByAggregateInput
  _max?: Prisma.TempVoiceChannelMaxOrderByAggregateInput
  _min?: Prisma.TempVoiceChannelMinOrderByAggregateInput
}

export type TempVoiceChannelScalarWhereWithAggregatesInput = {
  AND?: Prisma.TempVoiceChannelScalarWhereWithAggregatesInput | Prisma.TempVoiceChannelScalarWhereWithAggregatesInput[]
  OR?: Prisma.TempVoiceChannelScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TempVoiceChannelScalarWhereWithAggregatesInput | Prisma.TempVoiceChannelScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TempVoiceChannel"> | string
  systemId?: Prisma.StringWithAggregatesFilter<"TempVoiceChannel"> | string
  channelId?: Prisma.StringWithAggregatesFilter<"TempVoiceChannel"> | string
  ownerId?: Prisma.StringWithAggregatesFilter<"TempVoiceChannel"> | string
  templateType?: Prisma.EnumTempVoiceTypeWithAggregatesFilter<"TempVoiceChannel"> | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TempVoiceChannel"> | Date | string
  lastActiveAt?: Prisma.DateTimeWithAggregatesFilter<"TempVoiceChannel"> | Date | string
}

export type TempVoiceChannelCreateInput = {
  id?: string
  channelId: string
  ownerId: string
  templateType: $Enums.TempVoiceType
  createdAt?: Date | string
  lastActiveAt?: Date | string
  system: Prisma.TempVoiceSystemCreateNestedOneWithoutChannelsInput
}

export type TempVoiceChannelUncheckedCreateInput = {
  id?: string
  systemId: string
  channelId: string
  ownerId: string
  templateType: $Enums.TempVoiceType
  createdAt?: Date | string
  lastActiveAt?: Date | string
}

export type TempVoiceChannelUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  templateType?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastActiveAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  system?: Prisma.TempVoiceSystemUpdateOneRequiredWithoutChannelsNestedInput
}

export type TempVoiceChannelUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  systemId?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  templateType?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastActiveAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TempVoiceChannelCreateManyInput = {
  id?: string
  systemId: string
  channelId: string
  ownerId: string
  templateType: $Enums.TempVoiceType
  createdAt?: Date | string
  lastActiveAt?: Date | string
}

export type TempVoiceChannelUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  templateType?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastActiveAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TempVoiceChannelUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  systemId?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  templateType?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastActiveAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TempVoiceChannelListRelationFilter = {
  every?: Prisma.TempVoiceChannelWhereInput
  some?: Prisma.TempVoiceChannelWhereInput
  none?: Prisma.TempVoiceChannelWhereInput
}

export type TempVoiceChannelOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TempVoiceChannelCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  systemId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  templateType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  lastActiveAt?: Prisma.SortOrder
}

export type TempVoiceChannelMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  systemId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  templateType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  lastActiveAt?: Prisma.SortOrder
}

export type TempVoiceChannelMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  systemId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  templateType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  lastActiveAt?: Prisma.SortOrder
}

export type TempVoiceChannelCreateNestedManyWithoutSystemInput = {
  create?: Prisma.XOR<Prisma.TempVoiceChannelCreateWithoutSystemInput, Prisma.TempVoiceChannelUncheckedCreateWithoutSystemInput> | Prisma.TempVoiceChannelCreateWithoutSystemInput[] | Prisma.TempVoiceChannelUncheckedCreateWithoutSystemInput[]
  connectOrCreate?: Prisma.TempVoiceChannelCreateOrConnectWithoutSystemInput | Prisma.TempVoiceChannelCreateOrConnectWithoutSystemInput[]
  createMany?: Prisma.TempVoiceChannelCreateManySystemInputEnvelope
  connect?: Prisma.TempVoiceChannelWhereUniqueInput | Prisma.TempVoiceChannelWhereUniqueInput[]
}

export type TempVoiceChannelUncheckedCreateNestedManyWithoutSystemInput = {
  create?: Prisma.XOR<Prisma.TempVoiceChannelCreateWithoutSystemInput, Prisma.TempVoiceChannelUncheckedCreateWithoutSystemInput> | Prisma.TempVoiceChannelCreateWithoutSystemInput[] | Prisma.TempVoiceChannelUncheckedCreateWithoutSystemInput[]
  connectOrCreate?: Prisma.TempVoiceChannelCreateOrConnectWithoutSystemInput | Prisma.TempVoiceChannelCreateOrConnectWithoutSystemInput[]
  createMany?: Prisma.TempVoiceChannelCreateManySystemInputEnvelope
  connect?: Prisma.TempVoiceChannelWhereUniqueInput | Prisma.TempVoiceChannelWhereUniqueInput[]
}

export type TempVoiceChannelUpdateManyWithoutSystemNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceChannelCreateWithoutSystemInput, Prisma.TempVoiceChannelUncheckedCreateWithoutSystemInput> | Prisma.TempVoiceChannelCreateWithoutSystemInput[] | Prisma.TempVoiceChannelUncheckedCreateWithoutSystemInput[]
  connectOrCreate?: Prisma.TempVoiceChannelCreateOrConnectWithoutSystemInput | Prisma.TempVoiceChannelCreateOrConnectWithoutSystemInput[]
  upsert?: Prisma.TempVoiceChannelUpsertWithWhereUniqueWithoutSystemInput | Prisma.TempVoiceChannelUpsertWithWhereUniqueWithoutSystemInput[]
  createMany?: Prisma.TempVoiceChannelCreateManySystemInputEnvelope
  set?: Prisma.TempVoiceChannelWhereUniqueInput | Prisma.TempVoiceChannelWhereUniqueInput[]
  disconnect?: Prisma.TempVoiceChannelWhereUniqueInput | Prisma.TempVoiceChannelWhereUniqueInput[]
  delete?: Prisma.TempVoiceChannelWhereUniqueInput | Prisma.TempVoiceChannelWhereUniqueInput[]
  connect?: Prisma.TempVoiceChannelWhereUniqueInput | Prisma.TempVoiceChannelWhereUniqueInput[]
  update?: Prisma.TempVoiceChannelUpdateWithWhereUniqueWithoutSystemInput | Prisma.TempVoiceChannelUpdateWithWhereUniqueWithoutSystemInput[]
  updateMany?: Prisma.TempVoiceChannelUpdateManyWithWhereWithoutSystemInput | Prisma.TempVoiceChannelUpdateManyWithWhereWithoutSystemInput[]
  deleteMany?: Prisma.TempVoiceChannelScalarWhereInput | Prisma.TempVoiceChannelScalarWhereInput[]
}

export type TempVoiceChannelUncheckedUpdateManyWithoutSystemNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceChannelCreateWithoutSystemInput, Prisma.TempVoiceChannelUncheckedCreateWithoutSystemInput> | Prisma.TempVoiceChannelCreateWithoutSystemInput[] | Prisma.TempVoiceChannelUncheckedCreateWithoutSystemInput[]
  connectOrCreate?: Prisma.TempVoiceChannelCreateOrConnectWithoutSystemInput | Prisma.TempVoiceChannelCreateOrConnectWithoutSystemInput[]
  upsert?: Prisma.TempVoiceChannelUpsertWithWhereUniqueWithoutSystemInput | Prisma.TempVoiceChannelUpsertWithWhereUniqueWithoutSystemInput[]
  createMany?: Prisma.TempVoiceChannelCreateManySystemInputEnvelope
  set?: Prisma.TempVoiceChannelWhereUniqueInput | Prisma.TempVoiceChannelWhereUniqueInput[]
  disconnect?: Prisma.TempVoiceChannelWhereUniqueInput | Prisma.TempVoiceChannelWhereUniqueInput[]
  delete?: Prisma.TempVoiceChannelWhereUniqueInput | Prisma.TempVoiceChannelWhereUniqueInput[]
  connect?: Prisma.TempVoiceChannelWhereUniqueInput | Prisma.TempVoiceChannelWhereUniqueInput[]
  update?: Prisma.TempVoiceChannelUpdateWithWhereUniqueWithoutSystemInput | Prisma.TempVoiceChannelUpdateWithWhereUniqueWithoutSystemInput[]
  updateMany?: Prisma.TempVoiceChannelUpdateManyWithWhereWithoutSystemInput | Prisma.TempVoiceChannelUpdateManyWithWhereWithoutSystemInput[]
  deleteMany?: Prisma.TempVoiceChannelScalarWhereInput | Prisma.TempVoiceChannelScalarWhereInput[]
}

export type TempVoiceChannelCreateWithoutSystemInput = {
  id?: string
  channelId: string
  ownerId: string
  templateType: $Enums.TempVoiceType
  createdAt?: Date | string
  lastActiveAt?: Date | string
}

export type TempVoiceChannelUncheckedCreateWithoutSystemInput = {
  id?: string
  channelId: string
  ownerId: string
  templateType: $Enums.TempVoiceType
  createdAt?: Date | string
  lastActiveAt?: Date | string
}

export type TempVoiceChannelCreateOrConnectWithoutSystemInput = {
  where: Prisma.TempVoiceChannelWhereUniqueInput
  create: Prisma.XOR<Prisma.TempVoiceChannelCreateWithoutSystemInput, Prisma.TempVoiceChannelUncheckedCreateWithoutSystemInput>
}

export type TempVoiceChannelCreateManySystemInputEnvelope = {
  data: Prisma.TempVoiceChannelCreateManySystemInput | Prisma.TempVoiceChannelCreateManySystemInput[]
  skipDuplicates?: boolean
}

export type TempVoiceChannelUpsertWithWhereUniqueWithoutSystemInput = {
  where: Prisma.TempVoiceChannelWhereUniqueInput
  update: Prisma.XOR<Prisma.TempVoiceChannelUpdateWithoutSystemInput, Prisma.TempVoiceChannelUncheckedUpdateWithoutSystemInput>
  create: Prisma.XOR<Prisma.TempVoiceChannelCreateWithoutSystemInput, Prisma.TempVoiceChannelUncheckedCreateWithoutSystemInput>
}

export type TempVoiceChannelUpdateWithWhereUniqueWithoutSystemInput = {
  where: Prisma.TempVoiceChannelWhereUniqueInput
  data: Prisma.XOR<Prisma.TempVoiceChannelUpdateWithoutSystemInput, Prisma.TempVoiceChannelUncheckedUpdateWithoutSystemInput>
}

export type TempVoiceChannelUpdateManyWithWhereWithoutSystemInput = {
  where: Prisma.TempVoiceChannelScalarWhereInput
  data: Prisma.XOR<Prisma.TempVoiceChannelUpdateManyMutationInput, Prisma.TempVoiceChannelUncheckedUpdateManyWithoutSystemInput>
}

export type TempVoiceChannelScalarWhereInput = {
  AND?: Prisma.TempVoiceChannelScalarWhereInput | Prisma.TempVoiceChannelScalarWhereInput[]
  OR?: Prisma.TempVoiceChannelScalarWhereInput[]
  NOT?: Prisma.TempVoiceChannelScalarWhereInput | Prisma.TempVoiceChannelScalarWhereInput[]
  id?: Prisma.StringFilter<"TempVoiceChannel"> | string
  systemId?: Prisma.StringFilter<"TempVoiceChannel"> | string
  channelId?: Prisma.StringFilter<"TempVoiceChannel"> | string
  ownerId?: Prisma.StringFilter<"TempVoiceChannel"> | string
  templateType?: Prisma.EnumTempVoiceTypeFilter<"TempVoiceChannel"> | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFilter<"TempVoiceChannel"> | Date | string
  lastActiveAt?: Prisma.DateTimeFilter<"TempVoiceChannel"> | Date | string
}

export type TempVoiceChannelCreateManySystemInput = {
  id?: string
  channelId: string
  ownerId: string
  templateType: $Enums.TempVoiceType
  createdAt?: Date | string
  lastActiveAt?: Date | string
}

export type TempVoiceChannelUpdateWithoutSystemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  templateType?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastActiveAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TempVoiceChannelUncheckedUpdateWithoutSystemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  templateType?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastActiveAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TempVoiceChannelUncheckedUpdateManyWithoutSystemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  templateType?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastActiveAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TempVoiceChannelSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  systemId?: boolean
  channelId?: boolean
  ownerId?: boolean
  templateType?: boolean
  createdAt?: boolean
  lastActiveAt?: boolean
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoiceChannel"]>

export type TempVoiceChannelSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  systemId?: boolean
  channelId?: boolean
  ownerId?: boolean
  templateType?: boolean
  createdAt?: boolean
  lastActiveAt?: boolean
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoiceChannel"]>

export type TempVoiceChannelSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  systemId?: boolean
  channelId?: boolean
  ownerId?: boolean
  templateType?: boolean
  createdAt?: boolean
  lastActiveAt?: boolean
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoiceChannel"]>

export type TempVoiceChannelSelectScalar = {
  id?: boolean
  systemId?: boolean
  channelId?: boolean
  ownerId?: boolean
  templateType?: boolean
  createdAt?: boolean
  lastActiveAt?: boolean
}

export type TempVoiceChannelOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "systemId" | "channelId" | "ownerId" | "templateType" | "createdAt" | "lastActiveAt", ExtArgs["result"]["tempVoiceChannel"]>
export type TempVoiceChannelInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}
export type TempVoiceChannelIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}
export type TempVoiceChannelIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}

export type $TempVoiceChannelPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TempVoiceChannel"
  objects: {
    system: Prisma.$TempVoiceSystemPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    systemId: string
    channelId: string
    ownerId: string
    templateType: $Enums.TempVoiceType
    createdAt: Date
    lastActiveAt: Date
  }, ExtArgs["result"]["tempVoiceChannel"]>
  composites: {}
}

export type TempVoiceChannelGetPayload<S extends boolean | null | undefined | TempVoiceChannelDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelPayload, S>

export type TempVoiceChannelCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TempVoiceChannelFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TempVoiceChannelCountAggregateInputType | true
  }

export interface TempVoiceChannelDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TempVoiceChannel'], meta: { name: 'TempVoiceChannel' } }
  /**
   * Find zero or one TempVoiceChannel that matches the filter.
   * @param {TempVoiceChannelFindUniqueArgs} args - Arguments to find a TempVoiceChannel
   * @example
   * // Get one TempVoiceChannel
   * const tempVoiceChannel = await prisma.tempVoiceChannel.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TempVoiceChannelFindUniqueArgs>(args: Prisma.SelectSubset<T, TempVoiceChannelFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TempVoiceChannel that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TempVoiceChannelFindUniqueOrThrowArgs} args - Arguments to find a TempVoiceChannel
   * @example
   * // Get one TempVoiceChannel
   * const tempVoiceChannel = await prisma.tempVoiceChannel.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TempVoiceChannelFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TempVoiceChannelFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TempVoiceChannel that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceChannelFindFirstArgs} args - Arguments to find a TempVoiceChannel
   * @example
   * // Get one TempVoiceChannel
   * const tempVoiceChannel = await prisma.tempVoiceChannel.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TempVoiceChannelFindFirstArgs>(args?: Prisma.SelectSubset<T, TempVoiceChannelFindFirstArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TempVoiceChannel that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceChannelFindFirstOrThrowArgs} args - Arguments to find a TempVoiceChannel
   * @example
   * // Get one TempVoiceChannel
   * const tempVoiceChannel = await prisma.tempVoiceChannel.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TempVoiceChannelFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TempVoiceChannelFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TempVoiceChannels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceChannelFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TempVoiceChannels
   * const tempVoiceChannels = await prisma.tempVoiceChannel.findMany()
   * 
   * // Get first 10 TempVoiceChannels
   * const tempVoiceChannels = await prisma.tempVoiceChannel.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tempVoiceChannelWithIdOnly = await prisma.tempVoiceChannel.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TempVoiceChannelFindManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceChannelFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TempVoiceChannel.
   * @param {TempVoiceChannelCreateArgs} args - Arguments to create a TempVoiceChannel.
   * @example
   * // Create one TempVoiceChannel
   * const TempVoiceChannel = await prisma.tempVoiceChannel.create({
   *   data: {
   *     // ... data to create a TempVoiceChannel
   *   }
   * })
   * 
   */
  create<T extends TempVoiceChannelCreateArgs>(args: Prisma.SelectSubset<T, TempVoiceChannelCreateArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TempVoiceChannels.
   * @param {TempVoiceChannelCreateManyArgs} args - Arguments to create many TempVoiceChannels.
   * @example
   * // Create many TempVoiceChannels
   * const tempVoiceChannel = await prisma.tempVoiceChannel.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TempVoiceChannelCreateManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceChannelCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TempVoiceChannels and returns the data saved in the database.
   * @param {TempVoiceChannelCreateManyAndReturnArgs} args - Arguments to create many TempVoiceChannels.
   * @example
   * // Create many TempVoiceChannels
   * const tempVoiceChannel = await prisma.tempVoiceChannel.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TempVoiceChannels and only return the `id`
   * const tempVoiceChannelWithIdOnly = await prisma.tempVoiceChannel.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TempVoiceChannelCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TempVoiceChannelCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TempVoiceChannel.
   * @param {TempVoiceChannelDeleteArgs} args - Arguments to delete one TempVoiceChannel.
   * @example
   * // Delete one TempVoiceChannel
   * const TempVoiceChannel = await prisma.tempVoiceChannel.delete({
   *   where: {
   *     // ... filter to delete one TempVoiceChannel
   *   }
   * })
   * 
   */
  delete<T extends TempVoiceChannelDeleteArgs>(args: Prisma.SelectSubset<T, TempVoiceChannelDeleteArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TempVoiceChannel.
   * @param {TempVoiceChannelUpdateArgs} args - Arguments to update one TempVoiceChannel.
   * @example
   * // Update one TempVoiceChannel
   * const tempVoiceChannel = await prisma.tempVoiceChannel.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TempVoiceChannelUpdateArgs>(args: Prisma.SelectSubset<T, TempVoiceChannelUpdateArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TempVoiceChannels.
   * @param {TempVoiceChannelDeleteManyArgs} args - Arguments to filter TempVoiceChannels to delete.
   * @example
   * // Delete a few TempVoiceChannels
   * const { count } = await prisma.tempVoiceChannel.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TempVoiceChannelDeleteManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceChannelDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TempVoiceChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceChannelUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TempVoiceChannels
   * const tempVoiceChannel = await prisma.tempVoiceChannel.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TempVoiceChannelUpdateManyArgs>(args: Prisma.SelectSubset<T, TempVoiceChannelUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TempVoiceChannels and returns the data updated in the database.
   * @param {TempVoiceChannelUpdateManyAndReturnArgs} args - Arguments to update many TempVoiceChannels.
   * @example
   * // Update many TempVoiceChannels
   * const tempVoiceChannel = await prisma.tempVoiceChannel.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TempVoiceChannels and only return the `id`
   * const tempVoiceChannelWithIdOnly = await prisma.tempVoiceChannel.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TempVoiceChannelUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TempVoiceChannelUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TempVoiceChannel.
   * @param {TempVoiceChannelUpsertArgs} args - Arguments to update or create a TempVoiceChannel.
   * @example
   * // Update or create a TempVoiceChannel
   * const tempVoiceChannel = await prisma.tempVoiceChannel.upsert({
   *   create: {
   *     // ... data to create a TempVoiceChannel
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TempVoiceChannel we want to update
   *   }
   * })
   */
  upsert<T extends TempVoiceChannelUpsertArgs>(args: Prisma.SelectSubset<T, TempVoiceChannelUpsertArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TempVoiceChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceChannelCountArgs} args - Arguments to filter TempVoiceChannels to count.
   * @example
   * // Count the number of TempVoiceChannels
   * const count = await prisma.tempVoiceChannel.count({
   *   where: {
   *     // ... the filter for the TempVoiceChannels we want to count
   *   }
   * })
  **/
  count<T extends TempVoiceChannelCountArgs>(
    args?: Prisma.Subset<T, TempVoiceChannelCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TempVoiceChannelCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TempVoiceChannel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceChannelAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TempVoiceChannelAggregateArgs>(args: Prisma.Subset<T, TempVoiceChannelAggregateArgs>): Prisma.PrismaPromise<GetTempVoiceChannelAggregateType<T>>

  /**
   * Group by TempVoiceChannel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceChannelGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TempVoiceChannelGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TempVoiceChannelGroupByArgs['orderBy'] }
      : { orderBy?: TempVoiceChannelGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TempVoiceChannelGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTempVoiceChannelGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TempVoiceChannel model
 */
readonly fields: TempVoiceChannelFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TempVoiceChannel.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TempVoiceChannelClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  system<T extends Prisma.TempVoiceSystemDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TempVoiceSystemDefaultArgs<ExtArgs>>): Prisma.Prisma__TempVoiceSystemClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceSystemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TempVoiceChannel model
 */
export interface TempVoiceChannelFieldRefs {
  readonly id: Prisma.FieldRef<"TempVoiceChannel", 'String'>
  readonly systemId: Prisma.FieldRef<"TempVoiceChannel", 'String'>
  readonly channelId: Prisma.FieldRef<"TempVoiceChannel", 'String'>
  readonly ownerId: Prisma.FieldRef<"TempVoiceChannel", 'String'>
  readonly templateType: Prisma.FieldRef<"TempVoiceChannel", 'TempVoiceType'>
  readonly createdAt: Prisma.FieldRef<"TempVoiceChannel", 'DateTime'>
  readonly lastActiveAt: Prisma.FieldRef<"TempVoiceChannel", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TempVoiceChannel findUnique
 */
export type TempVoiceChannelFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannel
   */
  select?: Prisma.TempVoiceChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannel
   */
  omit?: Prisma.TempVoiceChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceChannel to fetch.
   */
  where: Prisma.TempVoiceChannelWhereUniqueInput
}

/**
 * TempVoiceChannel findUniqueOrThrow
 */
export type TempVoiceChannelFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannel
   */
  select?: Prisma.TempVoiceChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannel
   */
  omit?: Prisma.TempVoiceChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceChannel to fetch.
   */
  where: Prisma.TempVoiceChannelWhereUniqueInput
}

/**
 * TempVoiceChannel findFirst
 */
export type TempVoiceChannelFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannel
   */
  select?: Prisma.TempVoiceChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannel
   */
  omit?: Prisma.TempVoiceChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceChannel to fetch.
   */
  where?: Prisma.TempVoiceChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceChannels to fetch.
   */
  orderBy?: Prisma.TempVoiceChannelOrderByWithRelationInput | Prisma.TempVoiceChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TempVoiceChannels.
   */
  cursor?: Prisma.TempVoiceChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TempVoiceChannels.
   */
  distinct?: Prisma.TempVoiceChannelScalarFieldEnum | Prisma.TempVoiceChannelScalarFieldEnum[]
}

/**
 * TempVoiceChannel findFirstOrThrow
 */
export type TempVoiceChannelFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannel
   */
  select?: Prisma.TempVoiceChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannel
   */
  omit?: Prisma.TempVoiceChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceChannel to fetch.
   */
  where?: Prisma.TempVoiceChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceChannels to fetch.
   */
  orderBy?: Prisma.TempVoiceChannelOrderByWithRelationInput | Prisma.TempVoiceChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TempVoiceChannels.
   */
  cursor?: Prisma.TempVoiceChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TempVoiceChannels.
   */
  distinct?: Prisma.TempVoiceChannelScalarFieldEnum | Prisma.TempVoiceChannelScalarFieldEnum[]
}

/**
 * TempVoiceChannel findMany
 */
export type TempVoiceChannelFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannel
   */
  select?: Prisma.TempVoiceChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannel
   */
  omit?: Prisma.TempVoiceChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceChannels to fetch.
   */
  where?: Prisma.TempVoiceChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceChannels to fetch.
   */
  orderBy?: Prisma.TempVoiceChannelOrderByWithRelationInput | Prisma.TempVoiceChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TempVoiceChannels.
   */
  cursor?: Prisma.TempVoiceChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceChannels.
   */
  skip?: number
  distinct?: Prisma.TempVoiceChannelScalarFieldEnum | Prisma.TempVoiceChannelScalarFieldEnum[]
}

/**
 * TempVoiceChannel create
 */
export type TempVoiceChannelCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannel
   */
  select?: Prisma.TempVoiceChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannel
   */
  omit?: Prisma.TempVoiceChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelInclude<ExtArgs> | null
  /**
   * The data needed to create a TempVoiceChannel.
   */
  data: Prisma.XOR<Prisma.TempVoiceChannelCreateInput, Prisma.TempVoiceChannelUncheckedCreateInput>
}

/**
 * TempVoiceChannel createMany
 */
export type TempVoiceChannelCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TempVoiceChannels.
   */
  data: Prisma.TempVoiceChannelCreateManyInput | Prisma.TempVoiceChannelCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TempVoiceChannel createManyAndReturn
 */
export type TempVoiceChannelCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannel
   */
  select?: Prisma.TempVoiceChannelSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannel
   */
  omit?: Prisma.TempVoiceChannelOmit<ExtArgs> | null
  /**
   * The data used to create many TempVoiceChannels.
   */
  data: Prisma.TempVoiceChannelCreateManyInput | Prisma.TempVoiceChannelCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TempVoiceChannel update
 */
export type TempVoiceChannelUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannel
   */
  select?: Prisma.TempVoiceChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannel
   */
  omit?: Prisma.TempVoiceChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelInclude<ExtArgs> | null
  /**
   * The data needed to update a TempVoiceChannel.
   */
  data: Prisma.XOR<Prisma.TempVoiceChannelUpdateInput, Prisma.TempVoiceChannelUncheckedUpdateInput>
  /**
   * Choose, which TempVoiceChannel to update.
   */
  where: Prisma.TempVoiceChannelWhereUniqueInput
}

/**
 * TempVoiceChannel updateMany
 */
export type TempVoiceChannelUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TempVoiceChannels.
   */
  data: Prisma.XOR<Prisma.TempVoiceChannelUpdateManyMutationInput, Prisma.TempVoiceChannelUncheckedUpdateManyInput>
  /**
   * Filter which TempVoiceChannels to update
   */
  where?: Prisma.TempVoiceChannelWhereInput
  /**
   * Limit how many TempVoiceChannels to update.
   */
  limit?: number
}

/**
 * TempVoiceChannel updateManyAndReturn
 */
export type TempVoiceChannelUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannel
   */
  select?: Prisma.TempVoiceChannelSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannel
   */
  omit?: Prisma.TempVoiceChannelOmit<ExtArgs> | null
  /**
   * The data used to update TempVoiceChannels.
   */
  data: Prisma.XOR<Prisma.TempVoiceChannelUpdateManyMutationInput, Prisma.TempVoiceChannelUncheckedUpdateManyInput>
  /**
   * Filter which TempVoiceChannels to update
   */
  where?: Prisma.TempVoiceChannelWhereInput
  /**
   * Limit how many TempVoiceChannels to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TempVoiceChannel upsert
 */
export type TempVoiceChannelUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannel
   */
  select?: Prisma.TempVoiceChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannel
   */
  omit?: Prisma.TempVoiceChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelInclude<ExtArgs> | null
  /**
   * The filter to search for the TempVoiceChannel to update in case it exists.
   */
  where: Prisma.TempVoiceChannelWhereUniqueInput
  /**
   * In case the TempVoiceChannel found by the `where` argument doesn't exist, create a new TempVoiceChannel with this data.
   */
  create: Prisma.XOR<Prisma.TempVoiceChannelCreateInput, Prisma.TempVoiceChannelUncheckedCreateInput>
  /**
   * In case the TempVoiceChannel was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TempVoiceChannelUpdateInput, Prisma.TempVoiceChannelUncheckedUpdateInput>
}

/**
 * TempVoiceChannel delete
 */
export type TempVoiceChannelDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannel
   */
  select?: Prisma.TempVoiceChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannel
   */
  omit?: Prisma.TempVoiceChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelInclude<ExtArgs> | null
  /**
   * Filter which TempVoiceChannel to delete.
   */
  where: Prisma.TempVoiceChannelWhereUniqueInput
}

/**
 * TempVoiceChannel deleteMany
 */
export type TempVoiceChannelDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TempVoiceChannels to delete
   */
  where?: Prisma.TempVoiceChannelWhereInput
  /**
   * Limit how many TempVoiceChannels to delete.
   */
  limit?: number
}

/**
 * TempVoiceChannel without action
 */
export type TempVoiceChannelDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannel
   */
  select?: Prisma.TempVoiceChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannel
   */
  omit?: Prisma.TempVoiceChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelInclude<ExtArgs> | null
}
