
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TempVoiceTemplate` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TempVoiceTemplate
 * 
 */
export type TempVoiceTemplateModel = runtime.Types.Result.DefaultSelection<Prisma.$TempVoiceTemplatePayload>

export type AggregateTempVoiceTemplate = {
  _count: TempVoiceTemplateCountAggregateOutputType | null
  _avg: TempVoiceTemplateAvgAggregateOutputType | null
  _sum: TempVoiceTemplateSumAggregateOutputType | null
  _min: TempVoiceTemplateMinAggregateOutputType | null
  _max: TempVoiceTemplateMaxAggregateOutputType | null
}

export type TempVoiceTemplateAvgAggregateOutputType = {
  userLimit: number | null
  bitrate: number | null
}

export type TempVoiceTemplateSumAggregateOutputType = {
  userLimit: number | null
  bitrate: number | null
}

export type TempVoiceTemplateMinAggregateOutputType = {
  id: string | null
  type: $Enums.TempVoiceType | null
  nameTemplate: string | null
  userLimit: number | null
  bitrate: number | null
  createdAt: Date | null
  updatedAt: Date | null
  systemId: string | null
}

export type TempVoiceTemplateMaxAggregateOutputType = {
  id: string | null
  type: $Enums.TempVoiceType | null
  nameTemplate: string | null
  userLimit: number | null
  bitrate: number | null
  createdAt: Date | null
  updatedAt: Date | null
  systemId: string | null
}

export type TempVoiceTemplateCountAggregateOutputType = {
  id: number
  type: number
  nameTemplate: number
  userLimit: number
  bitrate: number
  createdAt: number
  updatedAt: number
  systemId: number
  _all: number
}


export type TempVoiceTemplateAvgAggregateInputType = {
  userLimit?: true
  bitrate?: true
}

export type TempVoiceTemplateSumAggregateInputType = {
  userLimit?: true
  bitrate?: true
}

export type TempVoiceTemplateMinAggregateInputType = {
  id?: true
  type?: true
  nameTemplate?: true
  userLimit?: true
  bitrate?: true
  createdAt?: true
  updatedAt?: true
  systemId?: true
}

export type TempVoiceTemplateMaxAggregateInputType = {
  id?: true
  type?: true
  nameTemplate?: true
  userLimit?: true
  bitrate?: true
  createdAt?: true
  updatedAt?: true
  systemId?: true
}

export type TempVoiceTemplateCountAggregateInputType = {
  id?: true
  type?: true
  nameTemplate?: true
  userLimit?: true
  bitrate?: true
  createdAt?: true
  updatedAt?: true
  systemId?: true
  _all?: true
}

export type TempVoiceTemplateAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TempVoiceTemplate to aggregate.
   */
  where?: Prisma.TempVoiceTemplateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceTemplates to fetch.
   */
  orderBy?: Prisma.TempVoiceTemplateOrderByWithRelationInput | Prisma.TempVoiceTemplateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TempVoiceTemplateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceTemplates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceTemplates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TempVoiceTemplates
  **/
  _count?: true | TempVoiceTemplateCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TempVoiceTemplateAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TempVoiceTemplateSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TempVoiceTemplateMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TempVoiceTemplateMaxAggregateInputType
}

export type GetTempVoiceTemplateAggregateType<T extends TempVoiceTemplateAggregateArgs> = {
      [P in keyof T & keyof AggregateTempVoiceTemplate]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTempVoiceTemplate[P]>
    : Prisma.GetScalarType<T[P], AggregateTempVoiceTemplate[P]>
}




export type TempVoiceTemplateGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TempVoiceTemplateWhereInput
  orderBy?: Prisma.TempVoiceTemplateOrderByWithAggregationInput | Prisma.TempVoiceTemplateOrderByWithAggregationInput[]
  by: Prisma.TempVoiceTemplateScalarFieldEnum[] | Prisma.TempVoiceTemplateScalarFieldEnum
  having?: Prisma.TempVoiceTemplateScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TempVoiceTemplateCountAggregateInputType | true
  _avg?: TempVoiceTemplateAvgAggregateInputType
  _sum?: TempVoiceTemplateSumAggregateInputType
  _min?: TempVoiceTemplateMinAggregateInputType
  _max?: TempVoiceTemplateMaxAggregateInputType
}

export type TempVoiceTemplateGroupByOutputType = {
  id: string
  type: $Enums.TempVoiceType
  nameTemplate: string
  userLimit: number | null
  bitrate: number | null
  createdAt: Date
  updatedAt: Date
  systemId: string
  _count: TempVoiceTemplateCountAggregateOutputType | null
  _avg: TempVoiceTemplateAvgAggregateOutputType | null
  _sum: TempVoiceTemplateSumAggregateOutputType | null
  _min: TempVoiceTemplateMinAggregateOutputType | null
  _max: TempVoiceTemplateMaxAggregateOutputType | null
}

type GetTempVoiceTemplateGroupByPayload<T extends TempVoiceTemplateGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TempVoiceTemplateGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TempVoiceTemplateGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TempVoiceTemplateGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TempVoiceTemplateGroupByOutputType[P]>
      }
    >
  >



export type TempVoiceTemplateWhereInput = {
  AND?: Prisma.TempVoiceTemplateWhereInput | Prisma.TempVoiceTemplateWhereInput[]
  OR?: Prisma.TempVoiceTemplateWhereInput[]
  NOT?: Prisma.TempVoiceTemplateWhereInput | Prisma.TempVoiceTemplateWhereInput[]
  id?: Prisma.StringFilter<"TempVoiceTemplate"> | string
  type?: Prisma.EnumTempVoiceTypeFilter<"TempVoiceTemplate"> | $Enums.TempVoiceType
  nameTemplate?: Prisma.StringFilter<"TempVoiceTemplate"> | string
  userLimit?: Prisma.IntNullableFilter<"TempVoiceTemplate"> | number | null
  bitrate?: Prisma.IntNullableFilter<"TempVoiceTemplate"> | number | null
  createdAt?: Prisma.DateTimeFilter<"TempVoiceTemplate"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TempVoiceTemplate"> | Date | string
  systemId?: Prisma.StringFilter<"TempVoiceTemplate"> | string
  system?: Prisma.XOR<Prisma.TempVoiceSystemScalarRelationFilter, Prisma.TempVoiceSystemWhereInput>
}

export type TempVoiceTemplateOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  nameTemplate?: Prisma.SortOrder
  userLimit?: Prisma.SortOrderInput | Prisma.SortOrder
  bitrate?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  systemId?: Prisma.SortOrder
  system?: Prisma.TempVoiceSystemOrderByWithRelationInput
}

export type TempVoiceTemplateWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  systemId_type?: Prisma.TempVoiceTemplateSystemIdTypeCompoundUniqueInput
  AND?: Prisma.TempVoiceTemplateWhereInput | Prisma.TempVoiceTemplateWhereInput[]
  OR?: Prisma.TempVoiceTemplateWhereInput[]
  NOT?: Prisma.TempVoiceTemplateWhereInput | Prisma.TempVoiceTemplateWhereInput[]
  type?: Prisma.EnumTempVoiceTypeFilter<"TempVoiceTemplate"> | $Enums.TempVoiceType
  nameTemplate?: Prisma.StringFilter<"TempVoiceTemplate"> | string
  userLimit?: Prisma.IntNullableFilter<"TempVoiceTemplate"> | number | null
  bitrate?: Prisma.IntNullableFilter<"TempVoiceTemplate"> | number | null
  createdAt?: Prisma.DateTimeFilter<"TempVoiceTemplate"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TempVoiceTemplate"> | Date | string
  systemId?: Prisma.StringFilter<"TempVoiceTemplate"> | string
  system?: Prisma.XOR<Prisma.TempVoiceSystemScalarRelationFilter, Prisma.TempVoiceSystemWhereInput>
}, "id" | "systemId_type">

export type TempVoiceTemplateOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  nameTemplate?: Prisma.SortOrder
  userLimit?: Prisma.SortOrderInput | Prisma.SortOrder
  bitrate?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  systemId?: Prisma.SortOrder
  _count?: Prisma.TempVoiceTemplateCountOrderByAggregateInput
  _avg?: Prisma.TempVoiceTemplateAvgOrderByAggregateInput
  _max?: Prisma.TempVoiceTemplateMaxOrderByAggregateInput
  _min?: Prisma.TempVoiceTemplateMinOrderByAggregateInput
  _sum?: Prisma.TempVoiceTemplateSumOrderByAggregateInput
}

export type TempVoiceTemplateScalarWhereWithAggregatesInput = {
  AND?: Prisma.TempVoiceTemplateScalarWhereWithAggregatesInput | Prisma.TempVoiceTemplateScalarWhereWithAggregatesInput[]
  OR?: Prisma.TempVoiceTemplateScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TempVoiceTemplateScalarWhereWithAggregatesInput | Prisma.TempVoiceTemplateScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TempVoiceTemplate"> | string
  type?: Prisma.EnumTempVoiceTypeWithAggregatesFilter<"TempVoiceTemplate"> | $Enums.TempVoiceType
  nameTemplate?: Prisma.StringWithAggregatesFilter<"TempVoiceTemplate"> | string
  userLimit?: Prisma.IntNullableWithAggregatesFilter<"TempVoiceTemplate"> | number | null
  bitrate?: Prisma.IntNullableWithAggregatesFilter<"TempVoiceTemplate"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TempVoiceTemplate"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TempVoiceTemplate"> | Date | string
  systemId?: Prisma.StringWithAggregatesFilter<"TempVoiceTemplate"> | string
}

export type TempVoiceTemplateCreateInput = {
  id?: string
  type: $Enums.TempVoiceType
  nameTemplate: string
  userLimit?: number | null
  bitrate?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  system: Prisma.TempVoiceSystemCreateNestedOneWithoutTemplatesInput
}

export type TempVoiceTemplateUncheckedCreateInput = {
  id?: string
  type: $Enums.TempVoiceType
  nameTemplate: string
  userLimit?: number | null
  bitrate?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  systemId: string
}

export type TempVoiceTemplateUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  nameTemplate?: Prisma.StringFieldUpdateOperationsInput | string
  userLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bitrate?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  system?: Prisma.TempVoiceSystemUpdateOneRequiredWithoutTemplatesNestedInput
}

export type TempVoiceTemplateUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  nameTemplate?: Prisma.StringFieldUpdateOperationsInput | string
  userLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bitrate?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  systemId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TempVoiceTemplateCreateManyInput = {
  id?: string
  type: $Enums.TempVoiceType
  nameTemplate: string
  userLimit?: number | null
  bitrate?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  systemId: string
}

export type TempVoiceTemplateUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  nameTemplate?: Prisma.StringFieldUpdateOperationsInput | string
  userLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bitrate?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TempVoiceTemplateUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  nameTemplate?: Prisma.StringFieldUpdateOperationsInput | string
  userLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bitrate?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  systemId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TempVoiceTemplateListRelationFilter = {
  every?: Prisma.TempVoiceTemplateWhereInput
  some?: Prisma.TempVoiceTemplateWhereInput
  none?: Prisma.TempVoiceTemplateWhereInput
}

export type TempVoiceTemplateOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TempVoiceTemplateSystemIdTypeCompoundUniqueInput = {
  systemId: string
  type: $Enums.TempVoiceType
}

export type TempVoiceTemplateCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  nameTemplate?: Prisma.SortOrder
  userLimit?: Prisma.SortOrder
  bitrate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  systemId?: Prisma.SortOrder
}

export type TempVoiceTemplateAvgOrderByAggregateInput = {
  userLimit?: Prisma.SortOrder
  bitrate?: Prisma.SortOrder
}

export type TempVoiceTemplateMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  nameTemplate?: Prisma.SortOrder
  userLimit?: Prisma.SortOrder
  bitrate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  systemId?: Prisma.SortOrder
}

export type TempVoiceTemplateMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  nameTemplate?: Prisma.SortOrder
  userLimit?: Prisma.SortOrder
  bitrate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  systemId?: Prisma.SortOrder
}

export type TempVoiceTemplateSumOrderByAggregateInput = {
  userLimit?: Prisma.SortOrder
  bitrate?: Prisma.SortOrder
}

export type TempVoiceTemplateCreateNestedManyWithoutSystemInput = {
  create?: Prisma.XOR<Prisma.TempVoiceTemplateCreateWithoutSystemInput, Prisma.TempVoiceTemplateUncheckedCreateWithoutSystemInput> | Prisma.TempVoiceTemplateCreateWithoutSystemInput[] | Prisma.TempVoiceTemplateUncheckedCreateWithoutSystemInput[]
  connectOrCreate?: Prisma.TempVoiceTemplateCreateOrConnectWithoutSystemInput | Prisma.TempVoiceTemplateCreateOrConnectWithoutSystemInput[]
  createMany?: Prisma.TempVoiceTemplateCreateManySystemInputEnvelope
  connect?: Prisma.TempVoiceTemplateWhereUniqueInput | Prisma.TempVoiceTemplateWhereUniqueInput[]
}

export type TempVoiceTemplateUncheckedCreateNestedManyWithoutSystemInput = {
  create?: Prisma.XOR<Prisma.TempVoiceTemplateCreateWithoutSystemInput, Prisma.TempVoiceTemplateUncheckedCreateWithoutSystemInput> | Prisma.TempVoiceTemplateCreateWithoutSystemInput[] | Prisma.TempVoiceTemplateUncheckedCreateWithoutSystemInput[]
  connectOrCreate?: Prisma.TempVoiceTemplateCreateOrConnectWithoutSystemInput | Prisma.TempVoiceTemplateCreateOrConnectWithoutSystemInput[]
  createMany?: Prisma.TempVoiceTemplateCreateManySystemInputEnvelope
  connect?: Prisma.TempVoiceTemplateWhereUniqueInput | Prisma.TempVoiceTemplateWhereUniqueInput[]
}

export type TempVoiceTemplateUpdateManyWithoutSystemNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceTemplateCreateWithoutSystemInput, Prisma.TempVoiceTemplateUncheckedCreateWithoutSystemInput> | Prisma.TempVoiceTemplateCreateWithoutSystemInput[] | Prisma.TempVoiceTemplateUncheckedCreateWithoutSystemInput[]
  connectOrCreate?: Prisma.TempVoiceTemplateCreateOrConnectWithoutSystemInput | Prisma.TempVoiceTemplateCreateOrConnectWithoutSystemInput[]
  upsert?: Prisma.TempVoiceTemplateUpsertWithWhereUniqueWithoutSystemInput | Prisma.TempVoiceTemplateUpsertWithWhereUniqueWithoutSystemInput[]
  createMany?: Prisma.TempVoiceTemplateCreateManySystemInputEnvelope
  set?: Prisma.TempVoiceTemplateWhereUniqueInput | Prisma.TempVoiceTemplateWhereUniqueInput[]
  disconnect?: Prisma.TempVoiceTemplateWhereUniqueInput | Prisma.TempVoiceTemplateWhereUniqueInput[]
  delete?: Prisma.TempVoiceTemplateWhereUniqueInput | Prisma.TempVoiceTemplateWhereUniqueInput[]
  connect?: Prisma.TempVoiceTemplateWhereUniqueInput | Prisma.TempVoiceTemplateWhereUniqueInput[]
  update?: Prisma.TempVoiceTemplateUpdateWithWhereUniqueWithoutSystemInput | Prisma.TempVoiceTemplateUpdateWithWhereUniqueWithoutSystemInput[]
  updateMany?: Prisma.TempVoiceTemplateUpdateManyWithWhereWithoutSystemInput | Prisma.TempVoiceTemplateUpdateManyWithWhereWithoutSystemInput[]
  deleteMany?: Prisma.TempVoiceTemplateScalarWhereInput | Prisma.TempVoiceTemplateScalarWhereInput[]
}

export type TempVoiceTemplateUncheckedUpdateManyWithoutSystemNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceTemplateCreateWithoutSystemInput, Prisma.TempVoiceTemplateUncheckedCreateWithoutSystemInput> | Prisma.TempVoiceTemplateCreateWithoutSystemInput[] | Prisma.TempVoiceTemplateUncheckedCreateWithoutSystemInput[]
  connectOrCreate?: Prisma.TempVoiceTemplateCreateOrConnectWithoutSystemInput | Prisma.TempVoiceTemplateCreateOrConnectWithoutSystemInput[]
  upsert?: Prisma.TempVoiceTemplateUpsertWithWhereUniqueWithoutSystemInput | Prisma.TempVoiceTemplateUpsertWithWhereUniqueWithoutSystemInput[]
  createMany?: Prisma.TempVoiceTemplateCreateManySystemInputEnvelope
  set?: Prisma.TempVoiceTemplateWhereUniqueInput | Prisma.TempVoiceTemplateWhereUniqueInput[]
  disconnect?: Prisma.TempVoiceTemplateWhereUniqueInput | Prisma.TempVoiceTemplateWhereUniqueInput[]
  delete?: Prisma.TempVoiceTemplateWhereUniqueInput | Prisma.TempVoiceTemplateWhereUniqueInput[]
  connect?: Prisma.TempVoiceTemplateWhereUniqueInput | Prisma.TempVoiceTemplateWhereUniqueInput[]
  update?: Prisma.TempVoiceTemplateUpdateWithWhereUniqueWithoutSystemInput | Prisma.TempVoiceTemplateUpdateWithWhereUniqueWithoutSystemInput[]
  updateMany?: Prisma.TempVoiceTemplateUpdateManyWithWhereWithoutSystemInput | Prisma.TempVoiceTemplateUpdateManyWithWhereWithoutSystemInput[]
  deleteMany?: Prisma.TempVoiceTemplateScalarWhereInput | Prisma.TempVoiceTemplateScalarWhereInput[]
}

export type TempVoiceTemplateCreateWithoutSystemInput = {
  id?: string
  type: $Enums.TempVoiceType
  nameTemplate: string
  userLimit?: number | null
  bitrate?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TempVoiceTemplateUncheckedCreateWithoutSystemInput = {
  id?: string
  type: $Enums.TempVoiceType
  nameTemplate: string
  userLimit?: number | null
  bitrate?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TempVoiceTemplateCreateOrConnectWithoutSystemInput = {
  where: Prisma.TempVoiceTemplateWhereUniqueInput
  create: Prisma.XOR<Prisma.TempVoiceTemplateCreateWithoutSystemInput, Prisma.TempVoiceTemplateUncheckedCreateWithoutSystemInput>
}

export type TempVoiceTemplateCreateManySystemInputEnvelope = {
  data: Prisma.TempVoiceTemplateCreateManySystemInput | Prisma.TempVoiceTemplateCreateManySystemInput[]
  skipDuplicates?: boolean
}

export type TempVoiceTemplateUpsertWithWhereUniqueWithoutSystemInput = {
  where: Prisma.TempVoiceTemplateWhereUniqueInput
  update: Prisma.XOR<Prisma.TempVoiceTemplateUpdateWithoutSystemInput, Prisma.TempVoiceTemplateUncheckedUpdateWithoutSystemInput>
  create: Prisma.XOR<Prisma.TempVoiceTemplateCreateWithoutSystemInput, Prisma.TempVoiceTemplateUncheckedCreateWithoutSystemInput>
}

export type TempVoiceTemplateUpdateWithWhereUniqueWithoutSystemInput = {
  where: Prisma.TempVoiceTemplateWhereUniqueInput
  data: Prisma.XOR<Prisma.TempVoiceTemplateUpdateWithoutSystemInput, Prisma.TempVoiceTemplateUncheckedUpdateWithoutSystemInput>
}

export type TempVoiceTemplateUpdateManyWithWhereWithoutSystemInput = {
  where: Prisma.TempVoiceTemplateScalarWhereInput
  data: Prisma.XOR<Prisma.TempVoiceTemplateUpdateManyMutationInput, Prisma.TempVoiceTemplateUncheckedUpdateManyWithoutSystemInput>
}

export type TempVoiceTemplateScalarWhereInput = {
  AND?: Prisma.TempVoiceTemplateScalarWhereInput | Prisma.TempVoiceTemplateScalarWhereInput[]
  OR?: Prisma.TempVoiceTemplateScalarWhereInput[]
  NOT?: Prisma.TempVoiceTemplateScalarWhereInput | Prisma.TempVoiceTemplateScalarWhereInput[]
  id?: Prisma.StringFilter<"TempVoiceTemplate"> | string
  type?: Prisma.EnumTempVoiceTypeFilter<"TempVoiceTemplate"> | $Enums.TempVoiceType
  nameTemplate?: Prisma.StringFilter<"TempVoiceTemplate"> | string
  userLimit?: Prisma.IntNullableFilter<"TempVoiceTemplate"> | number | null
  bitrate?: Prisma.IntNullableFilter<"TempVoiceTemplate"> | number | null
  createdAt?: Prisma.DateTimeFilter<"TempVoiceTemplate"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TempVoiceTemplate"> | Date | string
  systemId?: Prisma.StringFilter<"TempVoiceTemplate"> | string
}

export type TempVoiceTemplateCreateManySystemInput = {
  id?: string
  type: $Enums.TempVoiceType
  nameTemplate: string
  userLimit?: number | null
  bitrate?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TempVoiceTemplateUpdateWithoutSystemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  nameTemplate?: Prisma.StringFieldUpdateOperationsInput | string
  userLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bitrate?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TempVoiceTemplateUncheckedUpdateWithoutSystemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  nameTemplate?: Prisma.StringFieldUpdateOperationsInput | string
  userLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bitrate?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TempVoiceTemplateUncheckedUpdateManyWithoutSystemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  nameTemplate?: Prisma.StringFieldUpdateOperationsInput | string
  userLimit?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bitrate?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TempVoiceTemplateSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  nameTemplate?: boolean
  userLimit?: boolean
  bitrate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  systemId?: boolean
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoiceTemplate"]>

export type TempVoiceTemplateSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  nameTemplate?: boolean
  userLimit?: boolean
  bitrate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  systemId?: boolean
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoiceTemplate"]>

export type TempVoiceTemplateSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  nameTemplate?: boolean
  userLimit?: boolean
  bitrate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  systemId?: boolean
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoiceTemplate"]>

export type TempVoiceTemplateSelectScalar = {
  id?: boolean
  type?: boolean
  nameTemplate?: boolean
  userLimit?: boolean
  bitrate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  systemId?: boolean
}

export type TempVoiceTemplateOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "nameTemplate" | "userLimit" | "bitrate" | "createdAt" | "updatedAt" | "systemId", ExtArgs["result"]["tempVoiceTemplate"]>
export type TempVoiceTemplateInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}
export type TempVoiceTemplateIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}
export type TempVoiceTemplateIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}

export type $TempVoiceTemplatePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TempVoiceTemplate"
  objects: {
    system: Prisma.$TempVoiceSystemPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    type: $Enums.TempVoiceType
    nameTemplate: string
    userLimit: number | null
    bitrate: number | null
    createdAt: Date
    updatedAt: Date
    systemId: string
  }, ExtArgs["result"]["tempVoiceTemplate"]>
  composites: {}
}

export type TempVoiceTemplateGetPayload<S extends boolean | null | undefined | TempVoiceTemplateDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TempVoiceTemplatePayload, S>

export type TempVoiceTemplateCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TempVoiceTemplateFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TempVoiceTemplateCountAggregateInputType | true
  }

export interface TempVoiceTemplateDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TempVoiceTemplate'], meta: { name: 'TempVoiceTemplate' } }
  /**
   * Find zero or one TempVoiceTemplate that matches the filter.
   * @param {TempVoiceTemplateFindUniqueArgs} args - Arguments to find a TempVoiceTemplate
   * @example
   * // Get one TempVoiceTemplate
   * const tempVoiceTemplate = await prisma.tempVoiceTemplate.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TempVoiceTemplateFindUniqueArgs>(args: Prisma.SelectSubset<T, TempVoiceTemplateFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TempVoiceTemplateClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceTemplatePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TempVoiceTemplate that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TempVoiceTemplateFindUniqueOrThrowArgs} args - Arguments to find a TempVoiceTemplate
   * @example
   * // Get one TempVoiceTemplate
   * const tempVoiceTemplate = await prisma.tempVoiceTemplate.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TempVoiceTemplateFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TempVoiceTemplateFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TempVoiceTemplateClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceTemplatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TempVoiceTemplate that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceTemplateFindFirstArgs} args - Arguments to find a TempVoiceTemplate
   * @example
   * // Get one TempVoiceTemplate
   * const tempVoiceTemplate = await prisma.tempVoiceTemplate.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TempVoiceTemplateFindFirstArgs>(args?: Prisma.SelectSubset<T, TempVoiceTemplateFindFirstArgs<ExtArgs>>): Prisma.Prisma__TempVoiceTemplateClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceTemplatePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TempVoiceTemplate that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceTemplateFindFirstOrThrowArgs} args - Arguments to find a TempVoiceTemplate
   * @example
   * // Get one TempVoiceTemplate
   * const tempVoiceTemplate = await prisma.tempVoiceTemplate.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TempVoiceTemplateFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TempVoiceTemplateFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TempVoiceTemplateClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceTemplatePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TempVoiceTemplates that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceTemplateFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TempVoiceTemplates
   * const tempVoiceTemplates = await prisma.tempVoiceTemplate.findMany()
   * 
   * // Get first 10 TempVoiceTemplates
   * const tempVoiceTemplates = await prisma.tempVoiceTemplate.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tempVoiceTemplateWithIdOnly = await prisma.tempVoiceTemplate.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TempVoiceTemplateFindManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceTemplateFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceTemplatePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TempVoiceTemplate.
   * @param {TempVoiceTemplateCreateArgs} args - Arguments to create a TempVoiceTemplate.
   * @example
   * // Create one TempVoiceTemplate
   * const TempVoiceTemplate = await prisma.tempVoiceTemplate.create({
   *   data: {
   *     // ... data to create a TempVoiceTemplate
   *   }
   * })
   * 
   */
  create<T extends TempVoiceTemplateCreateArgs>(args: Prisma.SelectSubset<T, TempVoiceTemplateCreateArgs<ExtArgs>>): Prisma.Prisma__TempVoiceTemplateClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceTemplatePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TempVoiceTemplates.
   * @param {TempVoiceTemplateCreateManyArgs} args - Arguments to create many TempVoiceTemplates.
   * @example
   * // Create many TempVoiceTemplates
   * const tempVoiceTemplate = await prisma.tempVoiceTemplate.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TempVoiceTemplateCreateManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceTemplateCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TempVoiceTemplates and returns the data saved in the database.
   * @param {TempVoiceTemplateCreateManyAndReturnArgs} args - Arguments to create many TempVoiceTemplates.
   * @example
   * // Create many TempVoiceTemplates
   * const tempVoiceTemplate = await prisma.tempVoiceTemplate.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TempVoiceTemplates and only return the `id`
   * const tempVoiceTemplateWithIdOnly = await prisma.tempVoiceTemplate.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TempVoiceTemplateCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TempVoiceTemplateCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceTemplatePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TempVoiceTemplate.
   * @param {TempVoiceTemplateDeleteArgs} args - Arguments to delete one TempVoiceTemplate.
   * @example
   * // Delete one TempVoiceTemplate
   * const TempVoiceTemplate = await prisma.tempVoiceTemplate.delete({
   *   where: {
   *     // ... filter to delete one TempVoiceTemplate
   *   }
   * })
   * 
   */
  delete<T extends TempVoiceTemplateDeleteArgs>(args: Prisma.SelectSubset<T, TempVoiceTemplateDeleteArgs<ExtArgs>>): Prisma.Prisma__TempVoiceTemplateClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceTemplatePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TempVoiceTemplate.
   * @param {TempVoiceTemplateUpdateArgs} args - Arguments to update one TempVoiceTemplate.
   * @example
   * // Update one TempVoiceTemplate
   * const tempVoiceTemplate = await prisma.tempVoiceTemplate.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TempVoiceTemplateUpdateArgs>(args: Prisma.SelectSubset<T, TempVoiceTemplateUpdateArgs<ExtArgs>>): Prisma.Prisma__TempVoiceTemplateClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceTemplatePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TempVoiceTemplates.
   * @param {TempVoiceTemplateDeleteManyArgs} args - Arguments to filter TempVoiceTemplates to delete.
   * @example
   * // Delete a few TempVoiceTemplates
   * const { count } = await prisma.tempVoiceTemplate.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TempVoiceTemplateDeleteManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceTemplateDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TempVoiceTemplates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceTemplateUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TempVoiceTemplates
   * const tempVoiceTemplate = await prisma.tempVoiceTemplate.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TempVoiceTemplateUpdateManyArgs>(args: Prisma.SelectSubset<T, TempVoiceTemplateUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TempVoiceTemplates and returns the data updated in the database.
   * @param {TempVoiceTemplateUpdateManyAndReturnArgs} args - Arguments to update many TempVoiceTemplates.
   * @example
   * // Update many TempVoiceTemplates
   * const tempVoiceTemplate = await prisma.tempVoiceTemplate.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TempVoiceTemplates and only return the `id`
   * const tempVoiceTemplateWithIdOnly = await prisma.tempVoiceTemplate.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TempVoiceTemplateUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TempVoiceTemplateUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceTemplatePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TempVoiceTemplate.
   * @param {TempVoiceTemplateUpsertArgs} args - Arguments to update or create a TempVoiceTemplate.
   * @example
   * // Update or create a TempVoiceTemplate
   * const tempVoiceTemplate = await prisma.tempVoiceTemplate.upsert({
   *   create: {
   *     // ... data to create a TempVoiceTemplate
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TempVoiceTemplate we want to update
   *   }
   * })
   */
  upsert<T extends TempVoiceTemplateUpsertArgs>(args: Prisma.SelectSubset<T, TempVoiceTemplateUpsertArgs<ExtArgs>>): Prisma.Prisma__TempVoiceTemplateClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceTemplatePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TempVoiceTemplates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceTemplateCountArgs} args - Arguments to filter TempVoiceTemplates to count.
   * @example
   * // Count the number of TempVoiceTemplates
   * const count = await prisma.tempVoiceTemplate.count({
   *   where: {
   *     // ... the filter for the TempVoiceTemplates we want to count
   *   }
   * })
  **/
  count<T extends TempVoiceTemplateCountArgs>(
    args?: Prisma.Subset<T, TempVoiceTemplateCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TempVoiceTemplateCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TempVoiceTemplate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceTemplateAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TempVoiceTemplateAggregateArgs>(args: Prisma.Subset<T, TempVoiceTemplateAggregateArgs>): Prisma.PrismaPromise<GetTempVoiceTemplateAggregateType<T>>

  /**
   * Group by TempVoiceTemplate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceTemplateGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TempVoiceTemplateGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TempVoiceTemplateGroupByArgs['orderBy'] }
      : { orderBy?: TempVoiceTemplateGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TempVoiceTemplateGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTempVoiceTemplateGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TempVoiceTemplate model
 */
readonly fields: TempVoiceTemplateFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TempVoiceTemplate.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TempVoiceTemplateClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  system<T extends Prisma.TempVoiceSystemDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TempVoiceSystemDefaultArgs<ExtArgs>>): Prisma.Prisma__TempVoiceSystemClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceSystemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TempVoiceTemplate model
 */
export interface TempVoiceTemplateFieldRefs {
  readonly id: Prisma.FieldRef<"TempVoiceTemplate", 'String'>
  readonly type: Prisma.FieldRef<"TempVoiceTemplate", 'TempVoiceType'>
  readonly nameTemplate: Prisma.FieldRef<"TempVoiceTemplate", 'String'>
  readonly userLimit: Prisma.FieldRef<"TempVoiceTemplate", 'Int'>
  readonly bitrate: Prisma.FieldRef<"TempVoiceTemplate", 'Int'>
  readonly createdAt: Prisma.FieldRef<"TempVoiceTemplate", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TempVoiceTemplate", 'DateTime'>
  readonly systemId: Prisma.FieldRef<"TempVoiceTemplate", 'String'>
}
    

// Custom InputTypes
/**
 * TempVoiceTemplate findUnique
 */
export type TempVoiceTemplateFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceTemplate
   */
  select?: Prisma.TempVoiceTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceTemplate
   */
  omit?: Prisma.TempVoiceTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceTemplateInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceTemplate to fetch.
   */
  where: Prisma.TempVoiceTemplateWhereUniqueInput
}

/**
 * TempVoiceTemplate findUniqueOrThrow
 */
export type TempVoiceTemplateFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceTemplate
   */
  select?: Prisma.TempVoiceTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceTemplate
   */
  omit?: Prisma.TempVoiceTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceTemplateInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceTemplate to fetch.
   */
  where: Prisma.TempVoiceTemplateWhereUniqueInput
}

/**
 * TempVoiceTemplate findFirst
 */
export type TempVoiceTemplateFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceTemplate
   */
  select?: Prisma.TempVoiceTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceTemplate
   */
  omit?: Prisma.TempVoiceTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceTemplateInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceTemplate to fetch.
   */
  where?: Prisma.TempVoiceTemplateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceTemplates to fetch.
   */
  orderBy?: Prisma.TempVoiceTemplateOrderByWithRelationInput | Prisma.TempVoiceTemplateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TempVoiceTemplates.
   */
  cursor?: Prisma.TempVoiceTemplateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceTemplates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceTemplates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TempVoiceTemplates.
   */
  distinct?: Prisma.TempVoiceTemplateScalarFieldEnum | Prisma.TempVoiceTemplateScalarFieldEnum[]
}

/**
 * TempVoiceTemplate findFirstOrThrow
 */
export type TempVoiceTemplateFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceTemplate
   */
  select?: Prisma.TempVoiceTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceTemplate
   */
  omit?: Prisma.TempVoiceTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceTemplateInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceTemplate to fetch.
   */
  where?: Prisma.TempVoiceTemplateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceTemplates to fetch.
   */
  orderBy?: Prisma.TempVoiceTemplateOrderByWithRelationInput | Prisma.TempVoiceTemplateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TempVoiceTemplates.
   */
  cursor?: Prisma.TempVoiceTemplateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceTemplates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceTemplates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TempVoiceTemplates.
   */
  distinct?: Prisma.TempVoiceTemplateScalarFieldEnum | Prisma.TempVoiceTemplateScalarFieldEnum[]
}

/**
 * TempVoiceTemplate findMany
 */
export type TempVoiceTemplateFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceTemplate
   */
  select?: Prisma.TempVoiceTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceTemplate
   */
  omit?: Prisma.TempVoiceTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceTemplateInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceTemplates to fetch.
   */
  where?: Prisma.TempVoiceTemplateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceTemplates to fetch.
   */
  orderBy?: Prisma.TempVoiceTemplateOrderByWithRelationInput | Prisma.TempVoiceTemplateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TempVoiceTemplates.
   */
  cursor?: Prisma.TempVoiceTemplateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceTemplates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceTemplates.
   */
  skip?: number
  distinct?: Prisma.TempVoiceTemplateScalarFieldEnum | Prisma.TempVoiceTemplateScalarFieldEnum[]
}

/**
 * TempVoiceTemplate create
 */
export type TempVoiceTemplateCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceTemplate
   */
  select?: Prisma.TempVoiceTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceTemplate
   */
  omit?: Prisma.TempVoiceTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceTemplateInclude<ExtArgs> | null
  /**
   * The data needed to create a TempVoiceTemplate.
   */
  data: Prisma.XOR<Prisma.TempVoiceTemplateCreateInput, Prisma.TempVoiceTemplateUncheckedCreateInput>
}

/**
 * TempVoiceTemplate createMany
 */
export type TempVoiceTemplateCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TempVoiceTemplates.
   */
  data: Prisma.TempVoiceTemplateCreateManyInput | Prisma.TempVoiceTemplateCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TempVoiceTemplate createManyAndReturn
 */
export type TempVoiceTemplateCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceTemplate
   */
  select?: Prisma.TempVoiceTemplateSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceTemplate
   */
  omit?: Prisma.TempVoiceTemplateOmit<ExtArgs> | null
  /**
   * The data used to create many TempVoiceTemplates.
   */
  data: Prisma.TempVoiceTemplateCreateManyInput | Prisma.TempVoiceTemplateCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceTemplateIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TempVoiceTemplate update
 */
export type TempVoiceTemplateUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceTemplate
   */
  select?: Prisma.TempVoiceTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceTemplate
   */
  omit?: Prisma.TempVoiceTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceTemplateInclude<ExtArgs> | null
  /**
   * The data needed to update a TempVoiceTemplate.
   */
  data: Prisma.XOR<Prisma.TempVoiceTemplateUpdateInput, Prisma.TempVoiceTemplateUncheckedUpdateInput>
  /**
   * Choose, which TempVoiceTemplate to update.
   */
  where: Prisma.TempVoiceTemplateWhereUniqueInput
}

/**
 * TempVoiceTemplate updateMany
 */
export type TempVoiceTemplateUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TempVoiceTemplates.
   */
  data: Prisma.XOR<Prisma.TempVoiceTemplateUpdateManyMutationInput, Prisma.TempVoiceTemplateUncheckedUpdateManyInput>
  /**
   * Filter which TempVoiceTemplates to update
   */
  where?: Prisma.TempVoiceTemplateWhereInput
  /**
   * Limit how many TempVoiceTemplates to update.
   */
  limit?: number
}

/**
 * TempVoiceTemplate updateManyAndReturn
 */
export type TempVoiceTemplateUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceTemplate
   */
  select?: Prisma.TempVoiceTemplateSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceTemplate
   */
  omit?: Prisma.TempVoiceTemplateOmit<ExtArgs> | null
  /**
   * The data used to update TempVoiceTemplates.
   */
  data: Prisma.XOR<Prisma.TempVoiceTemplateUpdateManyMutationInput, Prisma.TempVoiceTemplateUncheckedUpdateManyInput>
  /**
   * Filter which TempVoiceTemplates to update
   */
  where?: Prisma.TempVoiceTemplateWhereInput
  /**
   * Limit how many TempVoiceTemplates to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceTemplateIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TempVoiceTemplate upsert
 */
export type TempVoiceTemplateUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceTemplate
   */
  select?: Prisma.TempVoiceTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceTemplate
   */
  omit?: Prisma.TempVoiceTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceTemplateInclude<ExtArgs> | null
  /**
   * The filter to search for the TempVoiceTemplate to update in case it exists.
   */
  where: Prisma.TempVoiceTemplateWhereUniqueInput
  /**
   * In case the TempVoiceTemplate found by the `where` argument doesn't exist, create a new TempVoiceTemplate with this data.
   */
  create: Prisma.XOR<Prisma.TempVoiceTemplateCreateInput, Prisma.TempVoiceTemplateUncheckedCreateInput>
  /**
   * In case the TempVoiceTemplate was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TempVoiceTemplateUpdateInput, Prisma.TempVoiceTemplateUncheckedUpdateInput>
}

/**
 * TempVoiceTemplate delete
 */
export type TempVoiceTemplateDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceTemplate
   */
  select?: Prisma.TempVoiceTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceTemplate
   */
  omit?: Prisma.TempVoiceTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceTemplateInclude<ExtArgs> | null
  /**
   * Filter which TempVoiceTemplate to delete.
   */
  where: Prisma.TempVoiceTemplateWhereUniqueInput
}

/**
 * TempVoiceTemplate deleteMany
 */
export type TempVoiceTemplateDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TempVoiceTemplates to delete
   */
  where?: Prisma.TempVoiceTemplateWhereInput
  /**
   * Limit how many TempVoiceTemplates to delete.
   */
  limit?: number
}

/**
 * TempVoiceTemplate without action
 */
export type TempVoiceTemplateDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceTemplate
   */
  select?: Prisma.TempVoiceTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceTemplate
   */
  omit?: Prisma.TempVoiceTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceTemplateInclude<ExtArgs> | null
}
