
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TempVoiceSystem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TempVoiceSystem
 * 
 */
export type TempVoiceSystemModel = runtime.Types.Result.DefaultSelection<Prisma.$TempVoiceSystemPayload>

export type AggregateTempVoiceSystem = {
  _count: TempVoiceSystemCountAggregateOutputType | null
  _avg: TempVoiceSystemAvgAggregateOutputType | null
  _sum: TempVoiceSystemSumAggregateOutputType | null
  _min: TempVoiceSystemMinAggregateOutputType | null
  _max: TempVoiceSystemMaxAggregateOutputType | null
}

export type TempVoiceSystemAvgAggregateOutputType = {
  deleteDelay: number | null
}

export type TempVoiceSystemSumAggregateOutputType = {
  deleteDelay: number | null
}

export type TempVoiceSystemMinAggregateOutputType = {
  id: string | null
  guildId: string | null
  name: string | null
  categoryId: string | null
  enabled: boolean | null
  deleteDelay: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TempVoiceSystemMaxAggregateOutputType = {
  id: string | null
  guildId: string | null
  name: string | null
  categoryId: string | null
  enabled: boolean | null
  deleteDelay: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TempVoiceSystemCountAggregateOutputType = {
  id: number
  guildId: number
  name: number
  categoryId: number
  enabled: number
  deleteDelay: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TempVoiceSystemAvgAggregateInputType = {
  deleteDelay?: true
}

export type TempVoiceSystemSumAggregateInputType = {
  deleteDelay?: true
}

export type TempVoiceSystemMinAggregateInputType = {
  id?: true
  guildId?: true
  name?: true
  categoryId?: true
  enabled?: true
  deleteDelay?: true
  createdAt?: true
  updatedAt?: true
}

export type TempVoiceSystemMaxAggregateInputType = {
  id?: true
  guildId?: true
  name?: true
  categoryId?: true
  enabled?: true
  deleteDelay?: true
  createdAt?: true
  updatedAt?: true
}

export type TempVoiceSystemCountAggregateInputType = {
  id?: true
  guildId?: true
  name?: true
  categoryId?: true
  enabled?: true
  deleteDelay?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TempVoiceSystemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TempVoiceSystem to aggregate.
   */
  where?: Prisma.TempVoiceSystemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceSystems to fetch.
   */
  orderBy?: Prisma.TempVoiceSystemOrderByWithRelationInput | Prisma.TempVoiceSystemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TempVoiceSystemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceSystems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceSystems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TempVoiceSystems
  **/
  _count?: true | TempVoiceSystemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TempVoiceSystemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TempVoiceSystemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TempVoiceSystemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TempVoiceSystemMaxAggregateInputType
}

export type GetTempVoiceSystemAggregateType<T extends TempVoiceSystemAggregateArgs> = {
      [P in keyof T & keyof AggregateTempVoiceSystem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTempVoiceSystem[P]>
    : Prisma.GetScalarType<T[P], AggregateTempVoiceSystem[P]>
}




export type TempVoiceSystemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TempVoiceSystemWhereInput
  orderBy?: Prisma.TempVoiceSystemOrderByWithAggregationInput | Prisma.TempVoiceSystemOrderByWithAggregationInput[]
  by: Prisma.TempVoiceSystemScalarFieldEnum[] | Prisma.TempVoiceSystemScalarFieldEnum
  having?: Prisma.TempVoiceSystemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TempVoiceSystemCountAggregateInputType | true
  _avg?: TempVoiceSystemAvgAggregateInputType
  _sum?: TempVoiceSystemSumAggregateInputType
  _min?: TempVoiceSystemMinAggregateInputType
  _max?: TempVoiceSystemMaxAggregateInputType
}

export type TempVoiceSystemGroupByOutputType = {
  id: string
  guildId: string
  name: string
  categoryId: string
  enabled: boolean
  deleteDelay: number
  createdAt: Date
  updatedAt: Date
  _count: TempVoiceSystemCountAggregateOutputType | null
  _avg: TempVoiceSystemAvgAggregateOutputType | null
  _sum: TempVoiceSystemSumAggregateOutputType | null
  _min: TempVoiceSystemMinAggregateOutputType | null
  _max: TempVoiceSystemMaxAggregateOutputType | null
}

type GetTempVoiceSystemGroupByPayload<T extends TempVoiceSystemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TempVoiceSystemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TempVoiceSystemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TempVoiceSystemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TempVoiceSystemGroupByOutputType[P]>
      }
    >
  >



export type TempVoiceSystemWhereInput = {
  AND?: Prisma.TempVoiceSystemWhereInput | Prisma.TempVoiceSystemWhereInput[]
  OR?: Prisma.TempVoiceSystemWhereInput[]
  NOT?: Prisma.TempVoiceSystemWhereInput | Prisma.TempVoiceSystemWhereInput[]
  id?: Prisma.StringFilter<"TempVoiceSystem"> | string
  guildId?: Prisma.StringFilter<"TempVoiceSystem"> | string
  name?: Prisma.StringFilter<"TempVoiceSystem"> | string
  categoryId?: Prisma.StringFilter<"TempVoiceSystem"> | string
  enabled?: Prisma.BoolFilter<"TempVoiceSystem"> | boolean
  deleteDelay?: Prisma.IntFilter<"TempVoiceSystem"> | number
  createdAt?: Prisma.DateTimeFilter<"TempVoiceSystem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TempVoiceSystem"> | Date | string
  channels?: Prisma.TempVoiceChannelListRelationFilter
  joins?: Prisma.TempVoiceJoinChannelListRelationFilter
  guild?: Prisma.XOR<Prisma.GuildConfigScalarRelationFilter, Prisma.GuildConfigWhereInput>
  templates?: Prisma.TempVoiceTemplateListRelationFilter
}

export type TempVoiceSystemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  deleteDelay?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  channels?: Prisma.TempVoiceChannelOrderByRelationAggregateInput
  joins?: Prisma.TempVoiceJoinChannelOrderByRelationAggregateInput
  guild?: Prisma.GuildConfigOrderByWithRelationInput
  templates?: Prisma.TempVoiceTemplateOrderByRelationAggregateInput
}

export type TempVoiceSystemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.TempVoiceSystemWhereInput | Prisma.TempVoiceSystemWhereInput[]
  OR?: Prisma.TempVoiceSystemWhereInput[]
  NOT?: Prisma.TempVoiceSystemWhereInput | Prisma.TempVoiceSystemWhereInput[]
  guildId?: Prisma.StringFilter<"TempVoiceSystem"> | string
  categoryId?: Prisma.StringFilter<"TempVoiceSystem"> | string
  enabled?: Prisma.BoolFilter<"TempVoiceSystem"> | boolean
  deleteDelay?: Prisma.IntFilter<"TempVoiceSystem"> | number
  createdAt?: Prisma.DateTimeFilter<"TempVoiceSystem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TempVoiceSystem"> | Date | string
  channels?: Prisma.TempVoiceChannelListRelationFilter
  joins?: Prisma.TempVoiceJoinChannelListRelationFilter
  guild?: Prisma.XOR<Prisma.GuildConfigScalarRelationFilter, Prisma.GuildConfigWhereInput>
  templates?: Prisma.TempVoiceTemplateListRelationFilter
}, "id" | "name">

export type TempVoiceSystemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  deleteDelay?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TempVoiceSystemCountOrderByAggregateInput
  _avg?: Prisma.TempVoiceSystemAvgOrderByAggregateInput
  _max?: Prisma.TempVoiceSystemMaxOrderByAggregateInput
  _min?: Prisma.TempVoiceSystemMinOrderByAggregateInput
  _sum?: Prisma.TempVoiceSystemSumOrderByAggregateInput
}

export type TempVoiceSystemScalarWhereWithAggregatesInput = {
  AND?: Prisma.TempVoiceSystemScalarWhereWithAggregatesInput | Prisma.TempVoiceSystemScalarWhereWithAggregatesInput[]
  OR?: Prisma.TempVoiceSystemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TempVoiceSystemScalarWhereWithAggregatesInput | Prisma.TempVoiceSystemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TempVoiceSystem"> | string
  guildId?: Prisma.StringWithAggregatesFilter<"TempVoiceSystem"> | string
  name?: Prisma.StringWithAggregatesFilter<"TempVoiceSystem"> | string
  categoryId?: Prisma.StringWithAggregatesFilter<"TempVoiceSystem"> | string
  enabled?: Prisma.BoolWithAggregatesFilter<"TempVoiceSystem"> | boolean
  deleteDelay?: Prisma.IntWithAggregatesFilter<"TempVoiceSystem"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TempVoiceSystem"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TempVoiceSystem"> | Date | string
}

export type TempVoiceSystemCreateInput = {
  id?: string
  name: string
  categoryId: string
  enabled?: boolean
  deleteDelay?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  channels?: Prisma.TempVoiceChannelCreateNestedManyWithoutSystemInput
  joins?: Prisma.TempVoiceJoinChannelCreateNestedManyWithoutSystemInput
  guild: Prisma.GuildConfigCreateNestedOneWithoutTempVoiceSystemsInput
  templates?: Prisma.TempVoiceTemplateCreateNestedManyWithoutSystemInput
}

export type TempVoiceSystemUncheckedCreateInput = {
  id?: string
  guildId: string
  name: string
  categoryId: string
  enabled?: boolean
  deleteDelay?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  channels?: Prisma.TempVoiceChannelUncheckedCreateNestedManyWithoutSystemInput
  joins?: Prisma.TempVoiceJoinChannelUncheckedCreateNestedManyWithoutSystemInput
  templates?: Prisma.TempVoiceTemplateUncheckedCreateNestedManyWithoutSystemInput
}

export type TempVoiceSystemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleteDelay?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channels?: Prisma.TempVoiceChannelUpdateManyWithoutSystemNestedInput
  joins?: Prisma.TempVoiceJoinChannelUpdateManyWithoutSystemNestedInput
  guild?: Prisma.GuildConfigUpdateOneRequiredWithoutTempVoiceSystemsNestedInput
  templates?: Prisma.TempVoiceTemplateUpdateManyWithoutSystemNestedInput
}

export type TempVoiceSystemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleteDelay?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channels?: Prisma.TempVoiceChannelUncheckedUpdateManyWithoutSystemNestedInput
  joins?: Prisma.TempVoiceJoinChannelUncheckedUpdateManyWithoutSystemNestedInput
  templates?: Prisma.TempVoiceTemplateUncheckedUpdateManyWithoutSystemNestedInput
}

export type TempVoiceSystemCreateManyInput = {
  id?: string
  guildId: string
  name: string
  categoryId: string
  enabled?: boolean
  deleteDelay?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TempVoiceSystemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleteDelay?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TempVoiceSystemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleteDelay?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TempVoiceSystemListRelationFilter = {
  every?: Prisma.TempVoiceSystemWhereInput
  some?: Prisma.TempVoiceSystemWhereInput
  none?: Prisma.TempVoiceSystemWhereInput
}

export type TempVoiceSystemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TempVoiceSystemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  deleteDelay?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TempVoiceSystemAvgOrderByAggregateInput = {
  deleteDelay?: Prisma.SortOrder
}

export type TempVoiceSystemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  deleteDelay?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TempVoiceSystemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  deleteDelay?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TempVoiceSystemSumOrderByAggregateInput = {
  deleteDelay?: Prisma.SortOrder
}

export type TempVoiceSystemScalarRelationFilter = {
  is?: Prisma.TempVoiceSystemWhereInput
  isNot?: Prisma.TempVoiceSystemWhereInput
}

export type TempVoiceSystemCreateNestedManyWithoutGuildInput = {
  create?: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutGuildInput, Prisma.TempVoiceSystemUncheckedCreateWithoutGuildInput> | Prisma.TempVoiceSystemCreateWithoutGuildInput[] | Prisma.TempVoiceSystemUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.TempVoiceSystemCreateOrConnectWithoutGuildInput | Prisma.TempVoiceSystemCreateOrConnectWithoutGuildInput[]
  createMany?: Prisma.TempVoiceSystemCreateManyGuildInputEnvelope
  connect?: Prisma.TempVoiceSystemWhereUniqueInput | Prisma.TempVoiceSystemWhereUniqueInput[]
}

export type TempVoiceSystemUncheckedCreateNestedManyWithoutGuildInput = {
  create?: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutGuildInput, Prisma.TempVoiceSystemUncheckedCreateWithoutGuildInput> | Prisma.TempVoiceSystemCreateWithoutGuildInput[] | Prisma.TempVoiceSystemUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.TempVoiceSystemCreateOrConnectWithoutGuildInput | Prisma.TempVoiceSystemCreateOrConnectWithoutGuildInput[]
  createMany?: Prisma.TempVoiceSystemCreateManyGuildInputEnvelope
  connect?: Prisma.TempVoiceSystemWhereUniqueInput | Prisma.TempVoiceSystemWhereUniqueInput[]
}

export type TempVoiceSystemUpdateManyWithoutGuildNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutGuildInput, Prisma.TempVoiceSystemUncheckedCreateWithoutGuildInput> | Prisma.TempVoiceSystemCreateWithoutGuildInput[] | Prisma.TempVoiceSystemUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.TempVoiceSystemCreateOrConnectWithoutGuildInput | Prisma.TempVoiceSystemCreateOrConnectWithoutGuildInput[]
  upsert?: Prisma.TempVoiceSystemUpsertWithWhereUniqueWithoutGuildInput | Prisma.TempVoiceSystemUpsertWithWhereUniqueWithoutGuildInput[]
  createMany?: Prisma.TempVoiceSystemCreateManyGuildInputEnvelope
  set?: Prisma.TempVoiceSystemWhereUniqueInput | Prisma.TempVoiceSystemWhereUniqueInput[]
  disconnect?: Prisma.TempVoiceSystemWhereUniqueInput | Prisma.TempVoiceSystemWhereUniqueInput[]
  delete?: Prisma.TempVoiceSystemWhereUniqueInput | Prisma.TempVoiceSystemWhereUniqueInput[]
  connect?: Prisma.TempVoiceSystemWhereUniqueInput | Prisma.TempVoiceSystemWhereUniqueInput[]
  update?: Prisma.TempVoiceSystemUpdateWithWhereUniqueWithoutGuildInput | Prisma.TempVoiceSystemUpdateWithWhereUniqueWithoutGuildInput[]
  updateMany?: Prisma.TempVoiceSystemUpdateManyWithWhereWithoutGuildInput | Prisma.TempVoiceSystemUpdateManyWithWhereWithoutGuildInput[]
  deleteMany?: Prisma.TempVoiceSystemScalarWhereInput | Prisma.TempVoiceSystemScalarWhereInput[]
}

export type TempVoiceSystemUncheckedUpdateManyWithoutGuildNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutGuildInput, Prisma.TempVoiceSystemUncheckedCreateWithoutGuildInput> | Prisma.TempVoiceSystemCreateWithoutGuildInput[] | Prisma.TempVoiceSystemUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.TempVoiceSystemCreateOrConnectWithoutGuildInput | Prisma.TempVoiceSystemCreateOrConnectWithoutGuildInput[]
  upsert?: Prisma.TempVoiceSystemUpsertWithWhereUniqueWithoutGuildInput | Prisma.TempVoiceSystemUpsertWithWhereUniqueWithoutGuildInput[]
  createMany?: Prisma.TempVoiceSystemCreateManyGuildInputEnvelope
  set?: Prisma.TempVoiceSystemWhereUniqueInput | Prisma.TempVoiceSystemWhereUniqueInput[]
  disconnect?: Prisma.TempVoiceSystemWhereUniqueInput | Prisma.TempVoiceSystemWhereUniqueInput[]
  delete?: Prisma.TempVoiceSystemWhereUniqueInput | Prisma.TempVoiceSystemWhereUniqueInput[]
  connect?: Prisma.TempVoiceSystemWhereUniqueInput | Prisma.TempVoiceSystemWhereUniqueInput[]
  update?: Prisma.TempVoiceSystemUpdateWithWhereUniqueWithoutGuildInput | Prisma.TempVoiceSystemUpdateWithWhereUniqueWithoutGuildInput[]
  updateMany?: Prisma.TempVoiceSystemUpdateManyWithWhereWithoutGuildInput | Prisma.TempVoiceSystemUpdateManyWithWhereWithoutGuildInput[]
  deleteMany?: Prisma.TempVoiceSystemScalarWhereInput | Prisma.TempVoiceSystemScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type TempVoiceSystemCreateNestedOneWithoutJoinsInput = {
  create?: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutJoinsInput, Prisma.TempVoiceSystemUncheckedCreateWithoutJoinsInput>
  connectOrCreate?: Prisma.TempVoiceSystemCreateOrConnectWithoutJoinsInput
  connect?: Prisma.TempVoiceSystemWhereUniqueInput
}

export type TempVoiceSystemUpdateOneRequiredWithoutJoinsNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutJoinsInput, Prisma.TempVoiceSystemUncheckedCreateWithoutJoinsInput>
  connectOrCreate?: Prisma.TempVoiceSystemCreateOrConnectWithoutJoinsInput
  upsert?: Prisma.TempVoiceSystemUpsertWithoutJoinsInput
  connect?: Prisma.TempVoiceSystemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TempVoiceSystemUpdateToOneWithWhereWithoutJoinsInput, Prisma.TempVoiceSystemUpdateWithoutJoinsInput>, Prisma.TempVoiceSystemUncheckedUpdateWithoutJoinsInput>
}

export type TempVoiceSystemCreateNestedOneWithoutTemplatesInput = {
  create?: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutTemplatesInput, Prisma.TempVoiceSystemUncheckedCreateWithoutTemplatesInput>
  connectOrCreate?: Prisma.TempVoiceSystemCreateOrConnectWithoutTemplatesInput
  connect?: Prisma.TempVoiceSystemWhereUniqueInput
}

export type TempVoiceSystemUpdateOneRequiredWithoutTemplatesNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutTemplatesInput, Prisma.TempVoiceSystemUncheckedCreateWithoutTemplatesInput>
  connectOrCreate?: Prisma.TempVoiceSystemCreateOrConnectWithoutTemplatesInput
  upsert?: Prisma.TempVoiceSystemUpsertWithoutTemplatesInput
  connect?: Prisma.TempVoiceSystemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TempVoiceSystemUpdateToOneWithWhereWithoutTemplatesInput, Prisma.TempVoiceSystemUpdateWithoutTemplatesInput>, Prisma.TempVoiceSystemUncheckedUpdateWithoutTemplatesInput>
}

export type TempVoiceSystemCreateNestedOneWithoutChannelsInput = {
  create?: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutChannelsInput, Prisma.TempVoiceSystemUncheckedCreateWithoutChannelsInput>
  connectOrCreate?: Prisma.TempVoiceSystemCreateOrConnectWithoutChannelsInput
  connect?: Prisma.TempVoiceSystemWhereUniqueInput
}

export type TempVoiceSystemUpdateOneRequiredWithoutChannelsNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutChannelsInput, Prisma.TempVoiceSystemUncheckedCreateWithoutChannelsInput>
  connectOrCreate?: Prisma.TempVoiceSystemCreateOrConnectWithoutChannelsInput
  upsert?: Prisma.TempVoiceSystemUpsertWithoutChannelsInput
  connect?: Prisma.TempVoiceSystemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TempVoiceSystemUpdateToOneWithWhereWithoutChannelsInput, Prisma.TempVoiceSystemUpdateWithoutChannelsInput>, Prisma.TempVoiceSystemUncheckedUpdateWithoutChannelsInput>
}

export type TempVoiceSystemCreateWithoutGuildInput = {
  id?: string
  name: string
  categoryId: string
  enabled?: boolean
  deleteDelay?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  channels?: Prisma.TempVoiceChannelCreateNestedManyWithoutSystemInput
  joins?: Prisma.TempVoiceJoinChannelCreateNestedManyWithoutSystemInput
  templates?: Prisma.TempVoiceTemplateCreateNestedManyWithoutSystemInput
}

export type TempVoiceSystemUncheckedCreateWithoutGuildInput = {
  id?: string
  name: string
  categoryId: string
  enabled?: boolean
  deleteDelay?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  channels?: Prisma.TempVoiceChannelUncheckedCreateNestedManyWithoutSystemInput
  joins?: Prisma.TempVoiceJoinChannelUncheckedCreateNestedManyWithoutSystemInput
  templates?: Prisma.TempVoiceTemplateUncheckedCreateNestedManyWithoutSystemInput
}

export type TempVoiceSystemCreateOrConnectWithoutGuildInput = {
  where: Prisma.TempVoiceSystemWhereUniqueInput
  create: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutGuildInput, Prisma.TempVoiceSystemUncheckedCreateWithoutGuildInput>
}

export type TempVoiceSystemCreateManyGuildInputEnvelope = {
  data: Prisma.TempVoiceSystemCreateManyGuildInput | Prisma.TempVoiceSystemCreateManyGuildInput[]
  skipDuplicates?: boolean
}

export type TempVoiceSystemUpsertWithWhereUniqueWithoutGuildInput = {
  where: Prisma.TempVoiceSystemWhereUniqueInput
  update: Prisma.XOR<Prisma.TempVoiceSystemUpdateWithoutGuildInput, Prisma.TempVoiceSystemUncheckedUpdateWithoutGuildInput>
  create: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutGuildInput, Prisma.TempVoiceSystemUncheckedCreateWithoutGuildInput>
}

export type TempVoiceSystemUpdateWithWhereUniqueWithoutGuildInput = {
  where: Prisma.TempVoiceSystemWhereUniqueInput
  data: Prisma.XOR<Prisma.TempVoiceSystemUpdateWithoutGuildInput, Prisma.TempVoiceSystemUncheckedUpdateWithoutGuildInput>
}

export type TempVoiceSystemUpdateManyWithWhereWithoutGuildInput = {
  where: Prisma.TempVoiceSystemScalarWhereInput
  data: Prisma.XOR<Prisma.TempVoiceSystemUpdateManyMutationInput, Prisma.TempVoiceSystemUncheckedUpdateManyWithoutGuildInput>
}

export type TempVoiceSystemScalarWhereInput = {
  AND?: Prisma.TempVoiceSystemScalarWhereInput | Prisma.TempVoiceSystemScalarWhereInput[]
  OR?: Prisma.TempVoiceSystemScalarWhereInput[]
  NOT?: Prisma.TempVoiceSystemScalarWhereInput | Prisma.TempVoiceSystemScalarWhereInput[]
  id?: Prisma.StringFilter<"TempVoiceSystem"> | string
  guildId?: Prisma.StringFilter<"TempVoiceSystem"> | string
  name?: Prisma.StringFilter<"TempVoiceSystem"> | string
  categoryId?: Prisma.StringFilter<"TempVoiceSystem"> | string
  enabled?: Prisma.BoolFilter<"TempVoiceSystem"> | boolean
  deleteDelay?: Prisma.IntFilter<"TempVoiceSystem"> | number
  createdAt?: Prisma.DateTimeFilter<"TempVoiceSystem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TempVoiceSystem"> | Date | string
}

export type TempVoiceSystemCreateWithoutJoinsInput = {
  id?: string
  name: string
  categoryId: string
  enabled?: boolean
  deleteDelay?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  channels?: Prisma.TempVoiceChannelCreateNestedManyWithoutSystemInput
  guild: Prisma.GuildConfigCreateNestedOneWithoutTempVoiceSystemsInput
  templates?: Prisma.TempVoiceTemplateCreateNestedManyWithoutSystemInput
}

export type TempVoiceSystemUncheckedCreateWithoutJoinsInput = {
  id?: string
  guildId: string
  name: string
  categoryId: string
  enabled?: boolean
  deleteDelay?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  channels?: Prisma.TempVoiceChannelUncheckedCreateNestedManyWithoutSystemInput
  templates?: Prisma.TempVoiceTemplateUncheckedCreateNestedManyWithoutSystemInput
}

export type TempVoiceSystemCreateOrConnectWithoutJoinsInput = {
  where: Prisma.TempVoiceSystemWhereUniqueInput
  create: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutJoinsInput, Prisma.TempVoiceSystemUncheckedCreateWithoutJoinsInput>
}

export type TempVoiceSystemUpsertWithoutJoinsInput = {
  update: Prisma.XOR<Prisma.TempVoiceSystemUpdateWithoutJoinsInput, Prisma.TempVoiceSystemUncheckedUpdateWithoutJoinsInput>
  create: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutJoinsInput, Prisma.TempVoiceSystemUncheckedCreateWithoutJoinsInput>
  where?: Prisma.TempVoiceSystemWhereInput
}

export type TempVoiceSystemUpdateToOneWithWhereWithoutJoinsInput = {
  where?: Prisma.TempVoiceSystemWhereInput
  data: Prisma.XOR<Prisma.TempVoiceSystemUpdateWithoutJoinsInput, Prisma.TempVoiceSystemUncheckedUpdateWithoutJoinsInput>
}

export type TempVoiceSystemUpdateWithoutJoinsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleteDelay?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channels?: Prisma.TempVoiceChannelUpdateManyWithoutSystemNestedInput
  guild?: Prisma.GuildConfigUpdateOneRequiredWithoutTempVoiceSystemsNestedInput
  templates?: Prisma.TempVoiceTemplateUpdateManyWithoutSystemNestedInput
}

export type TempVoiceSystemUncheckedUpdateWithoutJoinsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleteDelay?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channels?: Prisma.TempVoiceChannelUncheckedUpdateManyWithoutSystemNestedInput
  templates?: Prisma.TempVoiceTemplateUncheckedUpdateManyWithoutSystemNestedInput
}

export type TempVoiceSystemCreateWithoutTemplatesInput = {
  id?: string
  name: string
  categoryId: string
  enabled?: boolean
  deleteDelay?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  channels?: Prisma.TempVoiceChannelCreateNestedManyWithoutSystemInput
  joins?: Prisma.TempVoiceJoinChannelCreateNestedManyWithoutSystemInput
  guild: Prisma.GuildConfigCreateNestedOneWithoutTempVoiceSystemsInput
}

export type TempVoiceSystemUncheckedCreateWithoutTemplatesInput = {
  id?: string
  guildId: string
  name: string
  categoryId: string
  enabled?: boolean
  deleteDelay?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  channels?: Prisma.TempVoiceChannelUncheckedCreateNestedManyWithoutSystemInput
  joins?: Prisma.TempVoiceJoinChannelUncheckedCreateNestedManyWithoutSystemInput
}

export type TempVoiceSystemCreateOrConnectWithoutTemplatesInput = {
  where: Prisma.TempVoiceSystemWhereUniqueInput
  create: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutTemplatesInput, Prisma.TempVoiceSystemUncheckedCreateWithoutTemplatesInput>
}

export type TempVoiceSystemUpsertWithoutTemplatesInput = {
  update: Prisma.XOR<Prisma.TempVoiceSystemUpdateWithoutTemplatesInput, Prisma.TempVoiceSystemUncheckedUpdateWithoutTemplatesInput>
  create: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutTemplatesInput, Prisma.TempVoiceSystemUncheckedCreateWithoutTemplatesInput>
  where?: Prisma.TempVoiceSystemWhereInput
}

export type TempVoiceSystemUpdateToOneWithWhereWithoutTemplatesInput = {
  where?: Prisma.TempVoiceSystemWhereInput
  data: Prisma.XOR<Prisma.TempVoiceSystemUpdateWithoutTemplatesInput, Prisma.TempVoiceSystemUncheckedUpdateWithoutTemplatesInput>
}

export type TempVoiceSystemUpdateWithoutTemplatesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleteDelay?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channels?: Prisma.TempVoiceChannelUpdateManyWithoutSystemNestedInput
  joins?: Prisma.TempVoiceJoinChannelUpdateManyWithoutSystemNestedInput
  guild?: Prisma.GuildConfigUpdateOneRequiredWithoutTempVoiceSystemsNestedInput
}

export type TempVoiceSystemUncheckedUpdateWithoutTemplatesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleteDelay?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channels?: Prisma.TempVoiceChannelUncheckedUpdateManyWithoutSystemNestedInput
  joins?: Prisma.TempVoiceJoinChannelUncheckedUpdateManyWithoutSystemNestedInput
}

export type TempVoiceSystemCreateWithoutChannelsInput = {
  id?: string
  name: string
  categoryId: string
  enabled?: boolean
  deleteDelay?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  joins?: Prisma.TempVoiceJoinChannelCreateNestedManyWithoutSystemInput
  guild: Prisma.GuildConfigCreateNestedOneWithoutTempVoiceSystemsInput
  templates?: Prisma.TempVoiceTemplateCreateNestedManyWithoutSystemInput
}

export type TempVoiceSystemUncheckedCreateWithoutChannelsInput = {
  id?: string
  guildId: string
  name: string
  categoryId: string
  enabled?: boolean
  deleteDelay?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  joins?: Prisma.TempVoiceJoinChannelUncheckedCreateNestedManyWithoutSystemInput
  templates?: Prisma.TempVoiceTemplateUncheckedCreateNestedManyWithoutSystemInput
}

export type TempVoiceSystemCreateOrConnectWithoutChannelsInput = {
  where: Prisma.TempVoiceSystemWhereUniqueInput
  create: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutChannelsInput, Prisma.TempVoiceSystemUncheckedCreateWithoutChannelsInput>
}

export type TempVoiceSystemUpsertWithoutChannelsInput = {
  update: Prisma.XOR<Prisma.TempVoiceSystemUpdateWithoutChannelsInput, Prisma.TempVoiceSystemUncheckedUpdateWithoutChannelsInput>
  create: Prisma.XOR<Prisma.TempVoiceSystemCreateWithoutChannelsInput, Prisma.TempVoiceSystemUncheckedCreateWithoutChannelsInput>
  where?: Prisma.TempVoiceSystemWhereInput
}

export type TempVoiceSystemUpdateToOneWithWhereWithoutChannelsInput = {
  where?: Prisma.TempVoiceSystemWhereInput
  data: Prisma.XOR<Prisma.TempVoiceSystemUpdateWithoutChannelsInput, Prisma.TempVoiceSystemUncheckedUpdateWithoutChannelsInput>
}

export type TempVoiceSystemUpdateWithoutChannelsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleteDelay?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  joins?: Prisma.TempVoiceJoinChannelUpdateManyWithoutSystemNestedInput
  guild?: Prisma.GuildConfigUpdateOneRequiredWithoutTempVoiceSystemsNestedInput
  templates?: Prisma.TempVoiceTemplateUpdateManyWithoutSystemNestedInput
}

export type TempVoiceSystemUncheckedUpdateWithoutChannelsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleteDelay?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  joins?: Prisma.TempVoiceJoinChannelUncheckedUpdateManyWithoutSystemNestedInput
  templates?: Prisma.TempVoiceTemplateUncheckedUpdateManyWithoutSystemNestedInput
}

export type TempVoiceSystemCreateManyGuildInput = {
  id?: string
  name: string
  categoryId: string
  enabled?: boolean
  deleteDelay?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TempVoiceSystemUpdateWithoutGuildInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleteDelay?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channels?: Prisma.TempVoiceChannelUpdateManyWithoutSystemNestedInput
  joins?: Prisma.TempVoiceJoinChannelUpdateManyWithoutSystemNestedInput
  templates?: Prisma.TempVoiceTemplateUpdateManyWithoutSystemNestedInput
}

export type TempVoiceSystemUncheckedUpdateWithoutGuildInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleteDelay?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channels?: Prisma.TempVoiceChannelUncheckedUpdateManyWithoutSystemNestedInput
  joins?: Prisma.TempVoiceJoinChannelUncheckedUpdateManyWithoutSystemNestedInput
  templates?: Prisma.TempVoiceTemplateUncheckedUpdateManyWithoutSystemNestedInput
}

export type TempVoiceSystemUncheckedUpdateManyWithoutGuildInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleteDelay?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TempVoiceSystemCountOutputType
 */

export type TempVoiceSystemCountOutputType = {
  channels: number
  joins: number
  templates: number
}

export type TempVoiceSystemCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  channels?: boolean | TempVoiceSystemCountOutputTypeCountChannelsArgs
  joins?: boolean | TempVoiceSystemCountOutputTypeCountJoinsArgs
  templates?: boolean | TempVoiceSystemCountOutputTypeCountTemplatesArgs
}

/**
 * TempVoiceSystemCountOutputType without action
 */
export type TempVoiceSystemCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceSystemCountOutputType
   */
  select?: Prisma.TempVoiceSystemCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TempVoiceSystemCountOutputType without action
 */
export type TempVoiceSystemCountOutputTypeCountChannelsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TempVoiceChannelWhereInput
}

/**
 * TempVoiceSystemCountOutputType without action
 */
export type TempVoiceSystemCountOutputTypeCountJoinsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TempVoiceJoinChannelWhereInput
}

/**
 * TempVoiceSystemCountOutputType without action
 */
export type TempVoiceSystemCountOutputTypeCountTemplatesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TempVoiceTemplateWhereInput
}


export type TempVoiceSystemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  name?: boolean
  categoryId?: boolean
  enabled?: boolean
  deleteDelay?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  channels?: boolean | Prisma.TempVoiceSystem$channelsArgs<ExtArgs>
  joins?: boolean | Prisma.TempVoiceSystem$joinsArgs<ExtArgs>
  guild?: boolean | Prisma.GuildConfigDefaultArgs<ExtArgs>
  templates?: boolean | Prisma.TempVoiceSystem$templatesArgs<ExtArgs>
  _count?: boolean | Prisma.TempVoiceSystemCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoiceSystem"]>

export type TempVoiceSystemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  name?: boolean
  categoryId?: boolean
  enabled?: boolean
  deleteDelay?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  guild?: boolean | Prisma.GuildConfigDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoiceSystem"]>

export type TempVoiceSystemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  name?: boolean
  categoryId?: boolean
  enabled?: boolean
  deleteDelay?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  guild?: boolean | Prisma.GuildConfigDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoiceSystem"]>

export type TempVoiceSystemSelectScalar = {
  id?: boolean
  guildId?: boolean
  name?: boolean
  categoryId?: boolean
  enabled?: boolean
  deleteDelay?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TempVoiceSystemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "guildId" | "name" | "categoryId" | "enabled" | "deleteDelay" | "createdAt" | "updatedAt", ExtArgs["result"]["tempVoiceSystem"]>
export type TempVoiceSystemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  channels?: boolean | Prisma.TempVoiceSystem$channelsArgs<ExtArgs>
  joins?: boolean | Prisma.TempVoiceSystem$joinsArgs<ExtArgs>
  guild?: boolean | Prisma.GuildConfigDefaultArgs<ExtArgs>
  templates?: boolean | Prisma.TempVoiceSystem$templatesArgs<ExtArgs>
  _count?: boolean | Prisma.TempVoiceSystemCountOutputTypeDefaultArgs<ExtArgs>
}
export type TempVoiceSystemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guild?: boolean | Prisma.GuildConfigDefaultArgs<ExtArgs>
}
export type TempVoiceSystemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guild?: boolean | Prisma.GuildConfigDefaultArgs<ExtArgs>
}

export type $TempVoiceSystemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TempVoiceSystem"
  objects: {
    channels: Prisma.$TempVoiceChannelPayload<ExtArgs>[]
    joins: Prisma.$TempVoiceJoinChannelPayload<ExtArgs>[]
    guild: Prisma.$GuildConfigPayload<ExtArgs>
    templates: Prisma.$TempVoiceTemplatePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    guildId: string
    name: string
    categoryId: string
    enabled: boolean
    deleteDelay: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["tempVoiceSystem"]>
  composites: {}
}

export type TempVoiceSystemGetPayload<S extends boolean | null | undefined | TempVoiceSystemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TempVoiceSystemPayload, S>

export type TempVoiceSystemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TempVoiceSystemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TempVoiceSystemCountAggregateInputType | true
  }

export interface TempVoiceSystemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TempVoiceSystem'], meta: { name: 'TempVoiceSystem' } }
  /**
   * Find zero or one TempVoiceSystem that matches the filter.
   * @param {TempVoiceSystemFindUniqueArgs} args - Arguments to find a TempVoiceSystem
   * @example
   * // Get one TempVoiceSystem
   * const tempVoiceSystem = await prisma.tempVoiceSystem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TempVoiceSystemFindUniqueArgs>(args: Prisma.SelectSubset<T, TempVoiceSystemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TempVoiceSystemClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceSystemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TempVoiceSystem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TempVoiceSystemFindUniqueOrThrowArgs} args - Arguments to find a TempVoiceSystem
   * @example
   * // Get one TempVoiceSystem
   * const tempVoiceSystem = await prisma.tempVoiceSystem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TempVoiceSystemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TempVoiceSystemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TempVoiceSystemClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceSystemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TempVoiceSystem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceSystemFindFirstArgs} args - Arguments to find a TempVoiceSystem
   * @example
   * // Get one TempVoiceSystem
   * const tempVoiceSystem = await prisma.tempVoiceSystem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TempVoiceSystemFindFirstArgs>(args?: Prisma.SelectSubset<T, TempVoiceSystemFindFirstArgs<ExtArgs>>): Prisma.Prisma__TempVoiceSystemClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceSystemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TempVoiceSystem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceSystemFindFirstOrThrowArgs} args - Arguments to find a TempVoiceSystem
   * @example
   * // Get one TempVoiceSystem
   * const tempVoiceSystem = await prisma.tempVoiceSystem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TempVoiceSystemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TempVoiceSystemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TempVoiceSystemClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceSystemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TempVoiceSystems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceSystemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TempVoiceSystems
   * const tempVoiceSystems = await prisma.tempVoiceSystem.findMany()
   * 
   * // Get first 10 TempVoiceSystems
   * const tempVoiceSystems = await prisma.tempVoiceSystem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tempVoiceSystemWithIdOnly = await prisma.tempVoiceSystem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TempVoiceSystemFindManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceSystemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceSystemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TempVoiceSystem.
   * @param {TempVoiceSystemCreateArgs} args - Arguments to create a TempVoiceSystem.
   * @example
   * // Create one TempVoiceSystem
   * const TempVoiceSystem = await prisma.tempVoiceSystem.create({
   *   data: {
   *     // ... data to create a TempVoiceSystem
   *   }
   * })
   * 
   */
  create<T extends TempVoiceSystemCreateArgs>(args: Prisma.SelectSubset<T, TempVoiceSystemCreateArgs<ExtArgs>>): Prisma.Prisma__TempVoiceSystemClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceSystemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TempVoiceSystems.
   * @param {TempVoiceSystemCreateManyArgs} args - Arguments to create many TempVoiceSystems.
   * @example
   * // Create many TempVoiceSystems
   * const tempVoiceSystem = await prisma.tempVoiceSystem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TempVoiceSystemCreateManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceSystemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TempVoiceSystems and returns the data saved in the database.
   * @param {TempVoiceSystemCreateManyAndReturnArgs} args - Arguments to create many TempVoiceSystems.
   * @example
   * // Create many TempVoiceSystems
   * const tempVoiceSystem = await prisma.tempVoiceSystem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TempVoiceSystems and only return the `id`
   * const tempVoiceSystemWithIdOnly = await prisma.tempVoiceSystem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TempVoiceSystemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TempVoiceSystemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceSystemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TempVoiceSystem.
   * @param {TempVoiceSystemDeleteArgs} args - Arguments to delete one TempVoiceSystem.
   * @example
   * // Delete one TempVoiceSystem
   * const TempVoiceSystem = await prisma.tempVoiceSystem.delete({
   *   where: {
   *     // ... filter to delete one TempVoiceSystem
   *   }
   * })
   * 
   */
  delete<T extends TempVoiceSystemDeleteArgs>(args: Prisma.SelectSubset<T, TempVoiceSystemDeleteArgs<ExtArgs>>): Prisma.Prisma__TempVoiceSystemClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceSystemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TempVoiceSystem.
   * @param {TempVoiceSystemUpdateArgs} args - Arguments to update one TempVoiceSystem.
   * @example
   * // Update one TempVoiceSystem
   * const tempVoiceSystem = await prisma.tempVoiceSystem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TempVoiceSystemUpdateArgs>(args: Prisma.SelectSubset<T, TempVoiceSystemUpdateArgs<ExtArgs>>): Prisma.Prisma__TempVoiceSystemClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceSystemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TempVoiceSystems.
   * @param {TempVoiceSystemDeleteManyArgs} args - Arguments to filter TempVoiceSystems to delete.
   * @example
   * // Delete a few TempVoiceSystems
   * const { count } = await prisma.tempVoiceSystem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TempVoiceSystemDeleteManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceSystemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TempVoiceSystems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceSystemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TempVoiceSystems
   * const tempVoiceSystem = await prisma.tempVoiceSystem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TempVoiceSystemUpdateManyArgs>(args: Prisma.SelectSubset<T, TempVoiceSystemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TempVoiceSystems and returns the data updated in the database.
   * @param {TempVoiceSystemUpdateManyAndReturnArgs} args - Arguments to update many TempVoiceSystems.
   * @example
   * // Update many TempVoiceSystems
   * const tempVoiceSystem = await prisma.tempVoiceSystem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TempVoiceSystems and only return the `id`
   * const tempVoiceSystemWithIdOnly = await prisma.tempVoiceSystem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TempVoiceSystemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TempVoiceSystemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceSystemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TempVoiceSystem.
   * @param {TempVoiceSystemUpsertArgs} args - Arguments to update or create a TempVoiceSystem.
   * @example
   * // Update or create a TempVoiceSystem
   * const tempVoiceSystem = await prisma.tempVoiceSystem.upsert({
   *   create: {
   *     // ... data to create a TempVoiceSystem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TempVoiceSystem we want to update
   *   }
   * })
   */
  upsert<T extends TempVoiceSystemUpsertArgs>(args: Prisma.SelectSubset<T, TempVoiceSystemUpsertArgs<ExtArgs>>): Prisma.Prisma__TempVoiceSystemClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceSystemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TempVoiceSystems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceSystemCountArgs} args - Arguments to filter TempVoiceSystems to count.
   * @example
   * // Count the number of TempVoiceSystems
   * const count = await prisma.tempVoiceSystem.count({
   *   where: {
   *     // ... the filter for the TempVoiceSystems we want to count
   *   }
   * })
  **/
  count<T extends TempVoiceSystemCountArgs>(
    args?: Prisma.Subset<T, TempVoiceSystemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TempVoiceSystemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TempVoiceSystem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceSystemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TempVoiceSystemAggregateArgs>(args: Prisma.Subset<T, TempVoiceSystemAggregateArgs>): Prisma.PrismaPromise<GetTempVoiceSystemAggregateType<T>>

  /**
   * Group by TempVoiceSystem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceSystemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TempVoiceSystemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TempVoiceSystemGroupByArgs['orderBy'] }
      : { orderBy?: TempVoiceSystemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TempVoiceSystemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTempVoiceSystemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TempVoiceSystem model
 */
readonly fields: TempVoiceSystemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TempVoiceSystem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TempVoiceSystemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  channels<T extends Prisma.TempVoiceSystem$channelsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TempVoiceSystem$channelsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  joins<T extends Prisma.TempVoiceSystem$joinsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TempVoiceSystem$joinsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceJoinChannelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  guild<T extends Prisma.GuildConfigDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GuildConfigDefaultArgs<ExtArgs>>): Prisma.Prisma__GuildConfigClient<runtime.Types.Result.GetResult<Prisma.$GuildConfigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  templates<T extends Prisma.TempVoiceSystem$templatesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TempVoiceSystem$templatesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceTemplatePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TempVoiceSystem model
 */
export interface TempVoiceSystemFieldRefs {
  readonly id: Prisma.FieldRef<"TempVoiceSystem", 'String'>
  readonly guildId: Prisma.FieldRef<"TempVoiceSystem", 'String'>
  readonly name: Prisma.FieldRef<"TempVoiceSystem", 'String'>
  readonly categoryId: Prisma.FieldRef<"TempVoiceSystem", 'String'>
  readonly enabled: Prisma.FieldRef<"TempVoiceSystem", 'Boolean'>
  readonly deleteDelay: Prisma.FieldRef<"TempVoiceSystem", 'Int'>
  readonly createdAt: Prisma.FieldRef<"TempVoiceSystem", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TempVoiceSystem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TempVoiceSystem findUnique
 */
export type TempVoiceSystemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceSystem
   */
  select?: Prisma.TempVoiceSystemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceSystem
   */
  omit?: Prisma.TempVoiceSystemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceSystemInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceSystem to fetch.
   */
  where: Prisma.TempVoiceSystemWhereUniqueInput
}

/**
 * TempVoiceSystem findUniqueOrThrow
 */
export type TempVoiceSystemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceSystem
   */
  select?: Prisma.TempVoiceSystemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceSystem
   */
  omit?: Prisma.TempVoiceSystemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceSystemInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceSystem to fetch.
   */
  where: Prisma.TempVoiceSystemWhereUniqueInput
}

/**
 * TempVoiceSystem findFirst
 */
export type TempVoiceSystemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceSystem
   */
  select?: Prisma.TempVoiceSystemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceSystem
   */
  omit?: Prisma.TempVoiceSystemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceSystemInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceSystem to fetch.
   */
  where?: Prisma.TempVoiceSystemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceSystems to fetch.
   */
  orderBy?: Prisma.TempVoiceSystemOrderByWithRelationInput | Prisma.TempVoiceSystemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TempVoiceSystems.
   */
  cursor?: Prisma.TempVoiceSystemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceSystems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceSystems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TempVoiceSystems.
   */
  distinct?: Prisma.TempVoiceSystemScalarFieldEnum | Prisma.TempVoiceSystemScalarFieldEnum[]
}

/**
 * TempVoiceSystem findFirstOrThrow
 */
export type TempVoiceSystemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceSystem
   */
  select?: Prisma.TempVoiceSystemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceSystem
   */
  omit?: Prisma.TempVoiceSystemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceSystemInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceSystem to fetch.
   */
  where?: Prisma.TempVoiceSystemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceSystems to fetch.
   */
  orderBy?: Prisma.TempVoiceSystemOrderByWithRelationInput | Prisma.TempVoiceSystemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TempVoiceSystems.
   */
  cursor?: Prisma.TempVoiceSystemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceSystems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceSystems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TempVoiceSystems.
   */
  distinct?: Prisma.TempVoiceSystemScalarFieldEnum | Prisma.TempVoiceSystemScalarFieldEnum[]
}

/**
 * TempVoiceSystem findMany
 */
export type TempVoiceSystemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceSystem
   */
  select?: Prisma.TempVoiceSystemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceSystem
   */
  omit?: Prisma.TempVoiceSystemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceSystemInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceSystems to fetch.
   */
  where?: Prisma.TempVoiceSystemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceSystems to fetch.
   */
  orderBy?: Prisma.TempVoiceSystemOrderByWithRelationInput | Prisma.TempVoiceSystemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TempVoiceSystems.
   */
  cursor?: Prisma.TempVoiceSystemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceSystems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceSystems.
   */
  skip?: number
  distinct?: Prisma.TempVoiceSystemScalarFieldEnum | Prisma.TempVoiceSystemScalarFieldEnum[]
}

/**
 * TempVoiceSystem create
 */
export type TempVoiceSystemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceSystem
   */
  select?: Prisma.TempVoiceSystemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceSystem
   */
  omit?: Prisma.TempVoiceSystemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceSystemInclude<ExtArgs> | null
  /**
   * The data needed to create a TempVoiceSystem.
   */
  data: Prisma.XOR<Prisma.TempVoiceSystemCreateInput, Prisma.TempVoiceSystemUncheckedCreateInput>
}

/**
 * TempVoiceSystem createMany
 */
export type TempVoiceSystemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TempVoiceSystems.
   */
  data: Prisma.TempVoiceSystemCreateManyInput | Prisma.TempVoiceSystemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TempVoiceSystem createManyAndReturn
 */
export type TempVoiceSystemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceSystem
   */
  select?: Prisma.TempVoiceSystemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceSystem
   */
  omit?: Prisma.TempVoiceSystemOmit<ExtArgs> | null
  /**
   * The data used to create many TempVoiceSystems.
   */
  data: Prisma.TempVoiceSystemCreateManyInput | Prisma.TempVoiceSystemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceSystemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TempVoiceSystem update
 */
export type TempVoiceSystemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceSystem
   */
  select?: Prisma.TempVoiceSystemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceSystem
   */
  omit?: Prisma.TempVoiceSystemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceSystemInclude<ExtArgs> | null
  /**
   * The data needed to update a TempVoiceSystem.
   */
  data: Prisma.XOR<Prisma.TempVoiceSystemUpdateInput, Prisma.TempVoiceSystemUncheckedUpdateInput>
  /**
   * Choose, which TempVoiceSystem to update.
   */
  where: Prisma.TempVoiceSystemWhereUniqueInput
}

/**
 * TempVoiceSystem updateMany
 */
export type TempVoiceSystemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TempVoiceSystems.
   */
  data: Prisma.XOR<Prisma.TempVoiceSystemUpdateManyMutationInput, Prisma.TempVoiceSystemUncheckedUpdateManyInput>
  /**
   * Filter which TempVoiceSystems to update
   */
  where?: Prisma.TempVoiceSystemWhereInput
  /**
   * Limit how many TempVoiceSystems to update.
   */
  limit?: number
}

/**
 * TempVoiceSystem updateManyAndReturn
 */
export type TempVoiceSystemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceSystem
   */
  select?: Prisma.TempVoiceSystemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceSystem
   */
  omit?: Prisma.TempVoiceSystemOmit<ExtArgs> | null
  /**
   * The data used to update TempVoiceSystems.
   */
  data: Prisma.XOR<Prisma.TempVoiceSystemUpdateManyMutationInput, Prisma.TempVoiceSystemUncheckedUpdateManyInput>
  /**
   * Filter which TempVoiceSystems to update
   */
  where?: Prisma.TempVoiceSystemWhereInput
  /**
   * Limit how many TempVoiceSystems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceSystemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TempVoiceSystem upsert
 */
export type TempVoiceSystemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceSystem
   */
  select?: Prisma.TempVoiceSystemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceSystem
   */
  omit?: Prisma.TempVoiceSystemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceSystemInclude<ExtArgs> | null
  /**
   * The filter to search for the TempVoiceSystem to update in case it exists.
   */
  where: Prisma.TempVoiceSystemWhereUniqueInput
  /**
   * In case the TempVoiceSystem found by the `where` argument doesn't exist, create a new TempVoiceSystem with this data.
   */
  create: Prisma.XOR<Prisma.TempVoiceSystemCreateInput, Prisma.TempVoiceSystemUncheckedCreateInput>
  /**
   * In case the TempVoiceSystem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TempVoiceSystemUpdateInput, Prisma.TempVoiceSystemUncheckedUpdateInput>
}

/**
 * TempVoiceSystem delete
 */
export type TempVoiceSystemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceSystem
   */
  select?: Prisma.TempVoiceSystemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceSystem
   */
  omit?: Prisma.TempVoiceSystemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceSystemInclude<ExtArgs> | null
  /**
   * Filter which TempVoiceSystem to delete.
   */
  where: Prisma.TempVoiceSystemWhereUniqueInput
}

/**
 * TempVoiceSystem deleteMany
 */
export type TempVoiceSystemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TempVoiceSystems to delete
   */
  where?: Prisma.TempVoiceSystemWhereInput
  /**
   * Limit how many TempVoiceSystems to delete.
   */
  limit?: number
}

/**
 * TempVoiceSystem.channels
 */
export type TempVoiceSystem$channelsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannel
   */
  select?: Prisma.TempVoiceChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannel
   */
  omit?: Prisma.TempVoiceChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelInclude<ExtArgs> | null
  where?: Prisma.TempVoiceChannelWhereInput
  orderBy?: Prisma.TempVoiceChannelOrderByWithRelationInput | Prisma.TempVoiceChannelOrderByWithRelationInput[]
  cursor?: Prisma.TempVoiceChannelWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TempVoiceChannelScalarFieldEnum | Prisma.TempVoiceChannelScalarFieldEnum[]
}

/**
 * TempVoiceSystem.joins
 */
export type TempVoiceSystem$joinsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceJoinChannel
   */
  select?: Prisma.TempVoiceJoinChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceJoinChannel
   */
  omit?: Prisma.TempVoiceJoinChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceJoinChannelInclude<ExtArgs> | null
  where?: Prisma.TempVoiceJoinChannelWhereInput
  orderBy?: Prisma.TempVoiceJoinChannelOrderByWithRelationInput | Prisma.TempVoiceJoinChannelOrderByWithRelationInput[]
  cursor?: Prisma.TempVoiceJoinChannelWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TempVoiceJoinChannelScalarFieldEnum | Prisma.TempVoiceJoinChannelScalarFieldEnum[]
}

/**
 * TempVoiceSystem.templates
 */
export type TempVoiceSystem$templatesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceTemplate
   */
  select?: Prisma.TempVoiceTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceTemplate
   */
  omit?: Prisma.TempVoiceTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceTemplateInclude<ExtArgs> | null
  where?: Prisma.TempVoiceTemplateWhereInput
  orderBy?: Prisma.TempVoiceTemplateOrderByWithRelationInput | Prisma.TempVoiceTemplateOrderByWithRelationInput[]
  cursor?: Prisma.TempVoiceTemplateWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TempVoiceTemplateScalarFieldEnum | Prisma.TempVoiceTemplateScalarFieldEnum[]
}

/**
 * TempVoiceSystem without action
 */
export type TempVoiceSystemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceSystem
   */
  select?: Prisma.TempVoiceSystemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceSystem
   */
  omit?: Prisma.TempVoiceSystemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceSystemInclude<ExtArgs> | null
}
