
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TempVoiceJoinChannel` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TempVoiceJoinChannel
 * 
 */
export type TempVoiceJoinChannelModel = runtime.Types.Result.DefaultSelection<Prisma.$TempVoiceJoinChannelPayload>

export type AggregateTempVoiceJoinChannel = {
  _count: TempVoiceJoinChannelCountAggregateOutputType | null
  _min: TempVoiceJoinChannelMinAggregateOutputType | null
  _max: TempVoiceJoinChannelMaxAggregateOutputType | null
}

export type TempVoiceJoinChannelMinAggregateOutputType = {
  id: string | null
  channelId: string | null
  templateType: $Enums.TempVoiceType | null
  createdAt: Date | null
  updatedAt: Date | null
  systemId: string | null
}

export type TempVoiceJoinChannelMaxAggregateOutputType = {
  id: string | null
  channelId: string | null
  templateType: $Enums.TempVoiceType | null
  createdAt: Date | null
  updatedAt: Date | null
  systemId: string | null
}

export type TempVoiceJoinChannelCountAggregateOutputType = {
  id: number
  channelId: number
  templateType: number
  createdAt: number
  updatedAt: number
  systemId: number
  _all: number
}


export type TempVoiceJoinChannelMinAggregateInputType = {
  id?: true
  channelId?: true
  templateType?: true
  createdAt?: true
  updatedAt?: true
  systemId?: true
}

export type TempVoiceJoinChannelMaxAggregateInputType = {
  id?: true
  channelId?: true
  templateType?: true
  createdAt?: true
  updatedAt?: true
  systemId?: true
}

export type TempVoiceJoinChannelCountAggregateInputType = {
  id?: true
  channelId?: true
  templateType?: true
  createdAt?: true
  updatedAt?: true
  systemId?: true
  _all?: true
}

export type TempVoiceJoinChannelAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TempVoiceJoinChannel to aggregate.
   */
  where?: Prisma.TempVoiceJoinChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceJoinChannels to fetch.
   */
  orderBy?: Prisma.TempVoiceJoinChannelOrderByWithRelationInput | Prisma.TempVoiceJoinChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TempVoiceJoinChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceJoinChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceJoinChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TempVoiceJoinChannels
  **/
  _count?: true | TempVoiceJoinChannelCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TempVoiceJoinChannelMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TempVoiceJoinChannelMaxAggregateInputType
}

export type GetTempVoiceJoinChannelAggregateType<T extends TempVoiceJoinChannelAggregateArgs> = {
      [P in keyof T & keyof AggregateTempVoiceJoinChannel]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTempVoiceJoinChannel[P]>
    : Prisma.GetScalarType<T[P], AggregateTempVoiceJoinChannel[P]>
}




export type TempVoiceJoinChannelGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TempVoiceJoinChannelWhereInput
  orderBy?: Prisma.TempVoiceJoinChannelOrderByWithAggregationInput | Prisma.TempVoiceJoinChannelOrderByWithAggregationInput[]
  by: Prisma.TempVoiceJoinChannelScalarFieldEnum[] | Prisma.TempVoiceJoinChannelScalarFieldEnum
  having?: Prisma.TempVoiceJoinChannelScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TempVoiceJoinChannelCountAggregateInputType | true
  _min?: TempVoiceJoinChannelMinAggregateInputType
  _max?: TempVoiceJoinChannelMaxAggregateInputType
}

export type TempVoiceJoinChannelGroupByOutputType = {
  id: string
  channelId: string
  templateType: $Enums.TempVoiceType
  createdAt: Date
  updatedAt: Date
  systemId: string
  _count: TempVoiceJoinChannelCountAggregateOutputType | null
  _min: TempVoiceJoinChannelMinAggregateOutputType | null
  _max: TempVoiceJoinChannelMaxAggregateOutputType | null
}

type GetTempVoiceJoinChannelGroupByPayload<T extends TempVoiceJoinChannelGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TempVoiceJoinChannelGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TempVoiceJoinChannelGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TempVoiceJoinChannelGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TempVoiceJoinChannelGroupByOutputType[P]>
      }
    >
  >



export type TempVoiceJoinChannelWhereInput = {
  AND?: Prisma.TempVoiceJoinChannelWhereInput | Prisma.TempVoiceJoinChannelWhereInput[]
  OR?: Prisma.TempVoiceJoinChannelWhereInput[]
  NOT?: Prisma.TempVoiceJoinChannelWhereInput | Prisma.TempVoiceJoinChannelWhereInput[]
  id?: Prisma.StringFilter<"TempVoiceJoinChannel"> | string
  channelId?: Prisma.StringFilter<"TempVoiceJoinChannel"> | string
  templateType?: Prisma.EnumTempVoiceTypeFilter<"TempVoiceJoinChannel"> | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFilter<"TempVoiceJoinChannel"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TempVoiceJoinChannel"> | Date | string
  systemId?: Prisma.StringFilter<"TempVoiceJoinChannel"> | string
  system?: Prisma.XOR<Prisma.TempVoiceSystemScalarRelationFilter, Prisma.TempVoiceSystemWhereInput>
}

export type TempVoiceJoinChannelOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  templateType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  systemId?: Prisma.SortOrder
  system?: Prisma.TempVoiceSystemOrderByWithRelationInput
}

export type TempVoiceJoinChannelWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  channelId?: string
  AND?: Prisma.TempVoiceJoinChannelWhereInput | Prisma.TempVoiceJoinChannelWhereInput[]
  OR?: Prisma.TempVoiceJoinChannelWhereInput[]
  NOT?: Prisma.TempVoiceJoinChannelWhereInput | Prisma.TempVoiceJoinChannelWhereInput[]
  templateType?: Prisma.EnumTempVoiceTypeFilter<"TempVoiceJoinChannel"> | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFilter<"TempVoiceJoinChannel"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TempVoiceJoinChannel"> | Date | string
  systemId?: Prisma.StringFilter<"TempVoiceJoinChannel"> | string
  system?: Prisma.XOR<Prisma.TempVoiceSystemScalarRelationFilter, Prisma.TempVoiceSystemWhereInput>
}, "id" | "channelId">

export type TempVoiceJoinChannelOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  templateType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  systemId?: Prisma.SortOrder
  _count?: Prisma.TempVoiceJoinChannelCountOrderByAggregateInput
  _max?: Prisma.TempVoiceJoinChannelMaxOrderByAggregateInput
  _min?: Prisma.TempVoiceJoinChannelMinOrderByAggregateInput
}

export type TempVoiceJoinChannelScalarWhereWithAggregatesInput = {
  AND?: Prisma.TempVoiceJoinChannelScalarWhereWithAggregatesInput | Prisma.TempVoiceJoinChannelScalarWhereWithAggregatesInput[]
  OR?: Prisma.TempVoiceJoinChannelScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TempVoiceJoinChannelScalarWhereWithAggregatesInput | Prisma.TempVoiceJoinChannelScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TempVoiceJoinChannel"> | string
  channelId?: Prisma.StringWithAggregatesFilter<"TempVoiceJoinChannel"> | string
  templateType?: Prisma.EnumTempVoiceTypeWithAggregatesFilter<"TempVoiceJoinChannel"> | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TempVoiceJoinChannel"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TempVoiceJoinChannel"> | Date | string
  systemId?: Prisma.StringWithAggregatesFilter<"TempVoiceJoinChannel"> | string
}

export type TempVoiceJoinChannelCreateInput = {
  id?: string
  channelId: string
  templateType: $Enums.TempVoiceType
  createdAt?: Date | string
  updatedAt?: Date | string
  system: Prisma.TempVoiceSystemCreateNestedOneWithoutJoinsInput
}

export type TempVoiceJoinChannelUncheckedCreateInput = {
  id?: string
  channelId: string
  templateType: $Enums.TempVoiceType
  createdAt?: Date | string
  updatedAt?: Date | string
  systemId: string
}

export type TempVoiceJoinChannelUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  templateType?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  system?: Prisma.TempVoiceSystemUpdateOneRequiredWithoutJoinsNestedInput
}

export type TempVoiceJoinChannelUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  templateType?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  systemId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TempVoiceJoinChannelCreateManyInput = {
  id?: string
  channelId: string
  templateType: $Enums.TempVoiceType
  createdAt?: Date | string
  updatedAt?: Date | string
  systemId: string
}

export type TempVoiceJoinChannelUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  templateType?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TempVoiceJoinChannelUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  templateType?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  systemId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TempVoiceJoinChannelListRelationFilter = {
  every?: Prisma.TempVoiceJoinChannelWhereInput
  some?: Prisma.TempVoiceJoinChannelWhereInput
  none?: Prisma.TempVoiceJoinChannelWhereInput
}

export type TempVoiceJoinChannelOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TempVoiceJoinChannelCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  templateType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  systemId?: Prisma.SortOrder
}

export type TempVoiceJoinChannelMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  templateType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  systemId?: Prisma.SortOrder
}

export type TempVoiceJoinChannelMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  templateType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  systemId?: Prisma.SortOrder
}

export type TempVoiceJoinChannelCreateNestedManyWithoutSystemInput = {
  create?: Prisma.XOR<Prisma.TempVoiceJoinChannelCreateWithoutSystemInput, Prisma.TempVoiceJoinChannelUncheckedCreateWithoutSystemInput> | Prisma.TempVoiceJoinChannelCreateWithoutSystemInput[] | Prisma.TempVoiceJoinChannelUncheckedCreateWithoutSystemInput[]
  connectOrCreate?: Prisma.TempVoiceJoinChannelCreateOrConnectWithoutSystemInput | Prisma.TempVoiceJoinChannelCreateOrConnectWithoutSystemInput[]
  createMany?: Prisma.TempVoiceJoinChannelCreateManySystemInputEnvelope
  connect?: Prisma.TempVoiceJoinChannelWhereUniqueInput | Prisma.TempVoiceJoinChannelWhereUniqueInput[]
}

export type TempVoiceJoinChannelUncheckedCreateNestedManyWithoutSystemInput = {
  create?: Prisma.XOR<Prisma.TempVoiceJoinChannelCreateWithoutSystemInput, Prisma.TempVoiceJoinChannelUncheckedCreateWithoutSystemInput> | Prisma.TempVoiceJoinChannelCreateWithoutSystemInput[] | Prisma.TempVoiceJoinChannelUncheckedCreateWithoutSystemInput[]
  connectOrCreate?: Prisma.TempVoiceJoinChannelCreateOrConnectWithoutSystemInput | Prisma.TempVoiceJoinChannelCreateOrConnectWithoutSystemInput[]
  createMany?: Prisma.TempVoiceJoinChannelCreateManySystemInputEnvelope
  connect?: Prisma.TempVoiceJoinChannelWhereUniqueInput | Prisma.TempVoiceJoinChannelWhereUniqueInput[]
}

export type TempVoiceJoinChannelUpdateManyWithoutSystemNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceJoinChannelCreateWithoutSystemInput, Prisma.TempVoiceJoinChannelUncheckedCreateWithoutSystemInput> | Prisma.TempVoiceJoinChannelCreateWithoutSystemInput[] | Prisma.TempVoiceJoinChannelUncheckedCreateWithoutSystemInput[]
  connectOrCreate?: Prisma.TempVoiceJoinChannelCreateOrConnectWithoutSystemInput | Prisma.TempVoiceJoinChannelCreateOrConnectWithoutSystemInput[]
  upsert?: Prisma.TempVoiceJoinChannelUpsertWithWhereUniqueWithoutSystemInput | Prisma.TempVoiceJoinChannelUpsertWithWhereUniqueWithoutSystemInput[]
  createMany?: Prisma.TempVoiceJoinChannelCreateManySystemInputEnvelope
  set?: Prisma.TempVoiceJoinChannelWhereUniqueInput | Prisma.TempVoiceJoinChannelWhereUniqueInput[]
  disconnect?: Prisma.TempVoiceJoinChannelWhereUniqueInput | Prisma.TempVoiceJoinChannelWhereUniqueInput[]
  delete?: Prisma.TempVoiceJoinChannelWhereUniqueInput | Prisma.TempVoiceJoinChannelWhereUniqueInput[]
  connect?: Prisma.TempVoiceJoinChannelWhereUniqueInput | Prisma.TempVoiceJoinChannelWhereUniqueInput[]
  update?: Prisma.TempVoiceJoinChannelUpdateWithWhereUniqueWithoutSystemInput | Prisma.TempVoiceJoinChannelUpdateWithWhereUniqueWithoutSystemInput[]
  updateMany?: Prisma.TempVoiceJoinChannelUpdateManyWithWhereWithoutSystemInput | Prisma.TempVoiceJoinChannelUpdateManyWithWhereWithoutSystemInput[]
  deleteMany?: Prisma.TempVoiceJoinChannelScalarWhereInput | Prisma.TempVoiceJoinChannelScalarWhereInput[]
}

export type TempVoiceJoinChannelUncheckedUpdateManyWithoutSystemNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceJoinChannelCreateWithoutSystemInput, Prisma.TempVoiceJoinChannelUncheckedCreateWithoutSystemInput> | Prisma.TempVoiceJoinChannelCreateWithoutSystemInput[] | Prisma.TempVoiceJoinChannelUncheckedCreateWithoutSystemInput[]
  connectOrCreate?: Prisma.TempVoiceJoinChannelCreateOrConnectWithoutSystemInput | Prisma.TempVoiceJoinChannelCreateOrConnectWithoutSystemInput[]
  upsert?: Prisma.TempVoiceJoinChannelUpsertWithWhereUniqueWithoutSystemInput | Prisma.TempVoiceJoinChannelUpsertWithWhereUniqueWithoutSystemInput[]
  createMany?: Prisma.TempVoiceJoinChannelCreateManySystemInputEnvelope
  set?: Prisma.TempVoiceJoinChannelWhereUniqueInput | Prisma.TempVoiceJoinChannelWhereUniqueInput[]
  disconnect?: Prisma.TempVoiceJoinChannelWhereUniqueInput | Prisma.TempVoiceJoinChannelWhereUniqueInput[]
  delete?: Prisma.TempVoiceJoinChannelWhereUniqueInput | Prisma.TempVoiceJoinChannelWhereUniqueInput[]
  connect?: Prisma.TempVoiceJoinChannelWhereUniqueInput | Prisma.TempVoiceJoinChannelWhereUniqueInput[]
  update?: Prisma.TempVoiceJoinChannelUpdateWithWhereUniqueWithoutSystemInput | Prisma.TempVoiceJoinChannelUpdateWithWhereUniqueWithoutSystemInput[]
  updateMany?: Prisma.TempVoiceJoinChannelUpdateManyWithWhereWithoutSystemInput | Prisma.TempVoiceJoinChannelUpdateManyWithWhereWithoutSystemInput[]
  deleteMany?: Prisma.TempVoiceJoinChannelScalarWhereInput | Prisma.TempVoiceJoinChannelScalarWhereInput[]
}

export type EnumTempVoiceTypeFieldUpdateOperationsInput = {
  set?: $Enums.TempVoiceType
}

export type TempVoiceJoinChannelCreateWithoutSystemInput = {
  id?: string
  channelId: string
  templateType: $Enums.TempVoiceType
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TempVoiceJoinChannelUncheckedCreateWithoutSystemInput = {
  id?: string
  channelId: string
  templateType: $Enums.TempVoiceType
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TempVoiceJoinChannelCreateOrConnectWithoutSystemInput = {
  where: Prisma.TempVoiceJoinChannelWhereUniqueInput
  create: Prisma.XOR<Prisma.TempVoiceJoinChannelCreateWithoutSystemInput, Prisma.TempVoiceJoinChannelUncheckedCreateWithoutSystemInput>
}

export type TempVoiceJoinChannelCreateManySystemInputEnvelope = {
  data: Prisma.TempVoiceJoinChannelCreateManySystemInput | Prisma.TempVoiceJoinChannelCreateManySystemInput[]
  skipDuplicates?: boolean
}

export type TempVoiceJoinChannelUpsertWithWhereUniqueWithoutSystemInput = {
  where: Prisma.TempVoiceJoinChannelWhereUniqueInput
  update: Prisma.XOR<Prisma.TempVoiceJoinChannelUpdateWithoutSystemInput, Prisma.TempVoiceJoinChannelUncheckedUpdateWithoutSystemInput>
  create: Prisma.XOR<Prisma.TempVoiceJoinChannelCreateWithoutSystemInput, Prisma.TempVoiceJoinChannelUncheckedCreateWithoutSystemInput>
}

export type TempVoiceJoinChannelUpdateWithWhereUniqueWithoutSystemInput = {
  where: Prisma.TempVoiceJoinChannelWhereUniqueInput
  data: Prisma.XOR<Prisma.TempVoiceJoinChannelUpdateWithoutSystemInput, Prisma.TempVoiceJoinChannelUncheckedUpdateWithoutSystemInput>
}

export type TempVoiceJoinChannelUpdateManyWithWhereWithoutSystemInput = {
  where: Prisma.TempVoiceJoinChannelScalarWhereInput
  data: Prisma.XOR<Prisma.TempVoiceJoinChannelUpdateManyMutationInput, Prisma.TempVoiceJoinChannelUncheckedUpdateManyWithoutSystemInput>
}

export type TempVoiceJoinChannelScalarWhereInput = {
  AND?: Prisma.TempVoiceJoinChannelScalarWhereInput | Prisma.TempVoiceJoinChannelScalarWhereInput[]
  OR?: Prisma.TempVoiceJoinChannelScalarWhereInput[]
  NOT?: Prisma.TempVoiceJoinChannelScalarWhereInput | Prisma.TempVoiceJoinChannelScalarWhereInput[]
  id?: Prisma.StringFilter<"TempVoiceJoinChannel"> | string
  channelId?: Prisma.StringFilter<"TempVoiceJoinChannel"> | string
  templateType?: Prisma.EnumTempVoiceTypeFilter<"TempVoiceJoinChannel"> | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFilter<"TempVoiceJoinChannel"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TempVoiceJoinChannel"> | Date | string
  systemId?: Prisma.StringFilter<"TempVoiceJoinChannel"> | string
}

export type TempVoiceJoinChannelCreateManySystemInput = {
  id?: string
  channelId: string
  templateType: $Enums.TempVoiceType
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TempVoiceJoinChannelUpdateWithoutSystemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  templateType?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TempVoiceJoinChannelUncheckedUpdateWithoutSystemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  templateType?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TempVoiceJoinChannelUncheckedUpdateManyWithoutSystemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  templateType?: Prisma.EnumTempVoiceTypeFieldUpdateOperationsInput | $Enums.TempVoiceType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TempVoiceJoinChannelSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channelId?: boolean
  templateType?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  systemId?: boolean
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoiceJoinChannel"]>

export type TempVoiceJoinChannelSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channelId?: boolean
  templateType?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  systemId?: boolean
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoiceJoinChannel"]>

export type TempVoiceJoinChannelSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channelId?: boolean
  templateType?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  systemId?: boolean
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoiceJoinChannel"]>

export type TempVoiceJoinChannelSelectScalar = {
  id?: boolean
  channelId?: boolean
  templateType?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  systemId?: boolean
}

export type TempVoiceJoinChannelOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "channelId" | "templateType" | "createdAt" | "updatedAt" | "systemId", ExtArgs["result"]["tempVoiceJoinChannel"]>
export type TempVoiceJoinChannelInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}
export type TempVoiceJoinChannelIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}
export type TempVoiceJoinChannelIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  system?: boolean | Prisma.TempVoiceSystemDefaultArgs<ExtArgs>
}

export type $TempVoiceJoinChannelPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TempVoiceJoinChannel"
  objects: {
    system: Prisma.$TempVoiceSystemPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    channelId: string
    templateType: $Enums.TempVoiceType
    createdAt: Date
    updatedAt: Date
    systemId: string
  }, ExtArgs["result"]["tempVoiceJoinChannel"]>
  composites: {}
}

export type TempVoiceJoinChannelGetPayload<S extends boolean | null | undefined | TempVoiceJoinChannelDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TempVoiceJoinChannelPayload, S>

export type TempVoiceJoinChannelCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TempVoiceJoinChannelFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TempVoiceJoinChannelCountAggregateInputType | true
  }

export interface TempVoiceJoinChannelDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TempVoiceJoinChannel'], meta: { name: 'TempVoiceJoinChannel' } }
  /**
   * Find zero or one TempVoiceJoinChannel that matches the filter.
   * @param {TempVoiceJoinChannelFindUniqueArgs} args - Arguments to find a TempVoiceJoinChannel
   * @example
   * // Get one TempVoiceJoinChannel
   * const tempVoiceJoinChannel = await prisma.tempVoiceJoinChannel.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TempVoiceJoinChannelFindUniqueArgs>(args: Prisma.SelectSubset<T, TempVoiceJoinChannelFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TempVoiceJoinChannelClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceJoinChannelPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TempVoiceJoinChannel that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TempVoiceJoinChannelFindUniqueOrThrowArgs} args - Arguments to find a TempVoiceJoinChannel
   * @example
   * // Get one TempVoiceJoinChannel
   * const tempVoiceJoinChannel = await prisma.tempVoiceJoinChannel.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TempVoiceJoinChannelFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TempVoiceJoinChannelFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TempVoiceJoinChannelClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceJoinChannelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TempVoiceJoinChannel that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceJoinChannelFindFirstArgs} args - Arguments to find a TempVoiceJoinChannel
   * @example
   * // Get one TempVoiceJoinChannel
   * const tempVoiceJoinChannel = await prisma.tempVoiceJoinChannel.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TempVoiceJoinChannelFindFirstArgs>(args?: Prisma.SelectSubset<T, TempVoiceJoinChannelFindFirstArgs<ExtArgs>>): Prisma.Prisma__TempVoiceJoinChannelClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceJoinChannelPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TempVoiceJoinChannel that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceJoinChannelFindFirstOrThrowArgs} args - Arguments to find a TempVoiceJoinChannel
   * @example
   * // Get one TempVoiceJoinChannel
   * const tempVoiceJoinChannel = await prisma.tempVoiceJoinChannel.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TempVoiceJoinChannelFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TempVoiceJoinChannelFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TempVoiceJoinChannelClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceJoinChannelPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TempVoiceJoinChannels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceJoinChannelFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TempVoiceJoinChannels
   * const tempVoiceJoinChannels = await prisma.tempVoiceJoinChannel.findMany()
   * 
   * // Get first 10 TempVoiceJoinChannels
   * const tempVoiceJoinChannels = await prisma.tempVoiceJoinChannel.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tempVoiceJoinChannelWithIdOnly = await prisma.tempVoiceJoinChannel.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TempVoiceJoinChannelFindManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceJoinChannelFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceJoinChannelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TempVoiceJoinChannel.
   * @param {TempVoiceJoinChannelCreateArgs} args - Arguments to create a TempVoiceJoinChannel.
   * @example
   * // Create one TempVoiceJoinChannel
   * const TempVoiceJoinChannel = await prisma.tempVoiceJoinChannel.create({
   *   data: {
   *     // ... data to create a TempVoiceJoinChannel
   *   }
   * })
   * 
   */
  create<T extends TempVoiceJoinChannelCreateArgs>(args: Prisma.SelectSubset<T, TempVoiceJoinChannelCreateArgs<ExtArgs>>): Prisma.Prisma__TempVoiceJoinChannelClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceJoinChannelPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TempVoiceJoinChannels.
   * @param {TempVoiceJoinChannelCreateManyArgs} args - Arguments to create many TempVoiceJoinChannels.
   * @example
   * // Create many TempVoiceJoinChannels
   * const tempVoiceJoinChannel = await prisma.tempVoiceJoinChannel.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TempVoiceJoinChannelCreateManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceJoinChannelCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TempVoiceJoinChannels and returns the data saved in the database.
   * @param {TempVoiceJoinChannelCreateManyAndReturnArgs} args - Arguments to create many TempVoiceJoinChannels.
   * @example
   * // Create many TempVoiceJoinChannels
   * const tempVoiceJoinChannel = await prisma.tempVoiceJoinChannel.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TempVoiceJoinChannels and only return the `id`
   * const tempVoiceJoinChannelWithIdOnly = await prisma.tempVoiceJoinChannel.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TempVoiceJoinChannelCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TempVoiceJoinChannelCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceJoinChannelPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TempVoiceJoinChannel.
   * @param {TempVoiceJoinChannelDeleteArgs} args - Arguments to delete one TempVoiceJoinChannel.
   * @example
   * // Delete one TempVoiceJoinChannel
   * const TempVoiceJoinChannel = await prisma.tempVoiceJoinChannel.delete({
   *   where: {
   *     // ... filter to delete one TempVoiceJoinChannel
   *   }
   * })
   * 
   */
  delete<T extends TempVoiceJoinChannelDeleteArgs>(args: Prisma.SelectSubset<T, TempVoiceJoinChannelDeleteArgs<ExtArgs>>): Prisma.Prisma__TempVoiceJoinChannelClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceJoinChannelPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TempVoiceJoinChannel.
   * @param {TempVoiceJoinChannelUpdateArgs} args - Arguments to update one TempVoiceJoinChannel.
   * @example
   * // Update one TempVoiceJoinChannel
   * const tempVoiceJoinChannel = await prisma.tempVoiceJoinChannel.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TempVoiceJoinChannelUpdateArgs>(args: Prisma.SelectSubset<T, TempVoiceJoinChannelUpdateArgs<ExtArgs>>): Prisma.Prisma__TempVoiceJoinChannelClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceJoinChannelPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TempVoiceJoinChannels.
   * @param {TempVoiceJoinChannelDeleteManyArgs} args - Arguments to filter TempVoiceJoinChannels to delete.
   * @example
   * // Delete a few TempVoiceJoinChannels
   * const { count } = await prisma.tempVoiceJoinChannel.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TempVoiceJoinChannelDeleteManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceJoinChannelDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TempVoiceJoinChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceJoinChannelUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TempVoiceJoinChannels
   * const tempVoiceJoinChannel = await prisma.tempVoiceJoinChannel.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TempVoiceJoinChannelUpdateManyArgs>(args: Prisma.SelectSubset<T, TempVoiceJoinChannelUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TempVoiceJoinChannels and returns the data updated in the database.
   * @param {TempVoiceJoinChannelUpdateManyAndReturnArgs} args - Arguments to update many TempVoiceJoinChannels.
   * @example
   * // Update many TempVoiceJoinChannels
   * const tempVoiceJoinChannel = await prisma.tempVoiceJoinChannel.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TempVoiceJoinChannels and only return the `id`
   * const tempVoiceJoinChannelWithIdOnly = await prisma.tempVoiceJoinChannel.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TempVoiceJoinChannelUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TempVoiceJoinChannelUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceJoinChannelPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TempVoiceJoinChannel.
   * @param {TempVoiceJoinChannelUpsertArgs} args - Arguments to update or create a TempVoiceJoinChannel.
   * @example
   * // Update or create a TempVoiceJoinChannel
   * const tempVoiceJoinChannel = await prisma.tempVoiceJoinChannel.upsert({
   *   create: {
   *     // ... data to create a TempVoiceJoinChannel
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TempVoiceJoinChannel we want to update
   *   }
   * })
   */
  upsert<T extends TempVoiceJoinChannelUpsertArgs>(args: Prisma.SelectSubset<T, TempVoiceJoinChannelUpsertArgs<ExtArgs>>): Prisma.Prisma__TempVoiceJoinChannelClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceJoinChannelPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TempVoiceJoinChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceJoinChannelCountArgs} args - Arguments to filter TempVoiceJoinChannels to count.
   * @example
   * // Count the number of TempVoiceJoinChannels
   * const count = await prisma.tempVoiceJoinChannel.count({
   *   where: {
   *     // ... the filter for the TempVoiceJoinChannels we want to count
   *   }
   * })
  **/
  count<T extends TempVoiceJoinChannelCountArgs>(
    args?: Prisma.Subset<T, TempVoiceJoinChannelCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TempVoiceJoinChannelCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TempVoiceJoinChannel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceJoinChannelAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TempVoiceJoinChannelAggregateArgs>(args: Prisma.Subset<T, TempVoiceJoinChannelAggregateArgs>): Prisma.PrismaPromise<GetTempVoiceJoinChannelAggregateType<T>>

  /**
   * Group by TempVoiceJoinChannel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceJoinChannelGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TempVoiceJoinChannelGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TempVoiceJoinChannelGroupByArgs['orderBy'] }
      : { orderBy?: TempVoiceJoinChannelGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TempVoiceJoinChannelGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTempVoiceJoinChannelGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TempVoiceJoinChannel model
 */
readonly fields: TempVoiceJoinChannelFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TempVoiceJoinChannel.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TempVoiceJoinChannelClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  system<T extends Prisma.TempVoiceSystemDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TempVoiceSystemDefaultArgs<ExtArgs>>): Prisma.Prisma__TempVoiceSystemClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceSystemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TempVoiceJoinChannel model
 */
export interface TempVoiceJoinChannelFieldRefs {
  readonly id: Prisma.FieldRef<"TempVoiceJoinChannel", 'String'>
  readonly channelId: Prisma.FieldRef<"TempVoiceJoinChannel", 'String'>
  readonly templateType: Prisma.FieldRef<"TempVoiceJoinChannel", 'TempVoiceType'>
  readonly createdAt: Prisma.FieldRef<"TempVoiceJoinChannel", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TempVoiceJoinChannel", 'DateTime'>
  readonly systemId: Prisma.FieldRef<"TempVoiceJoinChannel", 'String'>
}
    

// Custom InputTypes
/**
 * TempVoiceJoinChannel findUnique
 */
export type TempVoiceJoinChannelFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceJoinChannel
   */
  select?: Prisma.TempVoiceJoinChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceJoinChannel
   */
  omit?: Prisma.TempVoiceJoinChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceJoinChannelInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceJoinChannel to fetch.
   */
  where: Prisma.TempVoiceJoinChannelWhereUniqueInput
}

/**
 * TempVoiceJoinChannel findUniqueOrThrow
 */
export type TempVoiceJoinChannelFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceJoinChannel
   */
  select?: Prisma.TempVoiceJoinChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceJoinChannel
   */
  omit?: Prisma.TempVoiceJoinChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceJoinChannelInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceJoinChannel to fetch.
   */
  where: Prisma.TempVoiceJoinChannelWhereUniqueInput
}

/**
 * TempVoiceJoinChannel findFirst
 */
export type TempVoiceJoinChannelFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceJoinChannel
   */
  select?: Prisma.TempVoiceJoinChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceJoinChannel
   */
  omit?: Prisma.TempVoiceJoinChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceJoinChannelInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceJoinChannel to fetch.
   */
  where?: Prisma.TempVoiceJoinChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceJoinChannels to fetch.
   */
  orderBy?: Prisma.TempVoiceJoinChannelOrderByWithRelationInput | Prisma.TempVoiceJoinChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TempVoiceJoinChannels.
   */
  cursor?: Prisma.TempVoiceJoinChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceJoinChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceJoinChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TempVoiceJoinChannels.
   */
  distinct?: Prisma.TempVoiceJoinChannelScalarFieldEnum | Prisma.TempVoiceJoinChannelScalarFieldEnum[]
}

/**
 * TempVoiceJoinChannel findFirstOrThrow
 */
export type TempVoiceJoinChannelFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceJoinChannel
   */
  select?: Prisma.TempVoiceJoinChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceJoinChannel
   */
  omit?: Prisma.TempVoiceJoinChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceJoinChannelInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceJoinChannel to fetch.
   */
  where?: Prisma.TempVoiceJoinChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceJoinChannels to fetch.
   */
  orderBy?: Prisma.TempVoiceJoinChannelOrderByWithRelationInput | Prisma.TempVoiceJoinChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TempVoiceJoinChannels.
   */
  cursor?: Prisma.TempVoiceJoinChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceJoinChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceJoinChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TempVoiceJoinChannels.
   */
  distinct?: Prisma.TempVoiceJoinChannelScalarFieldEnum | Prisma.TempVoiceJoinChannelScalarFieldEnum[]
}

/**
 * TempVoiceJoinChannel findMany
 */
export type TempVoiceJoinChannelFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceJoinChannel
   */
  select?: Prisma.TempVoiceJoinChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceJoinChannel
   */
  omit?: Prisma.TempVoiceJoinChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceJoinChannelInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceJoinChannels to fetch.
   */
  where?: Prisma.TempVoiceJoinChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceJoinChannels to fetch.
   */
  orderBy?: Prisma.TempVoiceJoinChannelOrderByWithRelationInput | Prisma.TempVoiceJoinChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TempVoiceJoinChannels.
   */
  cursor?: Prisma.TempVoiceJoinChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceJoinChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceJoinChannels.
   */
  skip?: number
  distinct?: Prisma.TempVoiceJoinChannelScalarFieldEnum | Prisma.TempVoiceJoinChannelScalarFieldEnum[]
}

/**
 * TempVoiceJoinChannel create
 */
export type TempVoiceJoinChannelCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceJoinChannel
   */
  select?: Prisma.TempVoiceJoinChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceJoinChannel
   */
  omit?: Prisma.TempVoiceJoinChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceJoinChannelInclude<ExtArgs> | null
  /**
   * The data needed to create a TempVoiceJoinChannel.
   */
  data: Prisma.XOR<Prisma.TempVoiceJoinChannelCreateInput, Prisma.TempVoiceJoinChannelUncheckedCreateInput>
}

/**
 * TempVoiceJoinChannel createMany
 */
export type TempVoiceJoinChannelCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TempVoiceJoinChannels.
   */
  data: Prisma.TempVoiceJoinChannelCreateManyInput | Prisma.TempVoiceJoinChannelCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TempVoiceJoinChannel createManyAndReturn
 */
export type TempVoiceJoinChannelCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceJoinChannel
   */
  select?: Prisma.TempVoiceJoinChannelSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceJoinChannel
   */
  omit?: Prisma.TempVoiceJoinChannelOmit<ExtArgs> | null
  /**
   * The data used to create many TempVoiceJoinChannels.
   */
  data: Prisma.TempVoiceJoinChannelCreateManyInput | Prisma.TempVoiceJoinChannelCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceJoinChannelIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TempVoiceJoinChannel update
 */
export type TempVoiceJoinChannelUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceJoinChannel
   */
  select?: Prisma.TempVoiceJoinChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceJoinChannel
   */
  omit?: Prisma.TempVoiceJoinChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceJoinChannelInclude<ExtArgs> | null
  /**
   * The data needed to update a TempVoiceJoinChannel.
   */
  data: Prisma.XOR<Prisma.TempVoiceJoinChannelUpdateInput, Prisma.TempVoiceJoinChannelUncheckedUpdateInput>
  /**
   * Choose, which TempVoiceJoinChannel to update.
   */
  where: Prisma.TempVoiceJoinChannelWhereUniqueInput
}

/**
 * TempVoiceJoinChannel updateMany
 */
export type TempVoiceJoinChannelUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TempVoiceJoinChannels.
   */
  data: Prisma.XOR<Prisma.TempVoiceJoinChannelUpdateManyMutationInput, Prisma.TempVoiceJoinChannelUncheckedUpdateManyInput>
  /**
   * Filter which TempVoiceJoinChannels to update
   */
  where?: Prisma.TempVoiceJoinChannelWhereInput
  /**
   * Limit how many TempVoiceJoinChannels to update.
   */
  limit?: number
}

/**
 * TempVoiceJoinChannel updateManyAndReturn
 */
export type TempVoiceJoinChannelUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceJoinChannel
   */
  select?: Prisma.TempVoiceJoinChannelSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceJoinChannel
   */
  omit?: Prisma.TempVoiceJoinChannelOmit<ExtArgs> | null
  /**
   * The data used to update TempVoiceJoinChannels.
   */
  data: Prisma.XOR<Prisma.TempVoiceJoinChannelUpdateManyMutationInput, Prisma.TempVoiceJoinChannelUncheckedUpdateManyInput>
  /**
   * Filter which TempVoiceJoinChannels to update
   */
  where?: Prisma.TempVoiceJoinChannelWhereInput
  /**
   * Limit how many TempVoiceJoinChannels to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceJoinChannelIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TempVoiceJoinChannel upsert
 */
export type TempVoiceJoinChannelUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceJoinChannel
   */
  select?: Prisma.TempVoiceJoinChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceJoinChannel
   */
  omit?: Prisma.TempVoiceJoinChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceJoinChannelInclude<ExtArgs> | null
  /**
   * The filter to search for the TempVoiceJoinChannel to update in case it exists.
   */
  where: Prisma.TempVoiceJoinChannelWhereUniqueInput
  /**
   * In case the TempVoiceJoinChannel found by the `where` argument doesn't exist, create a new TempVoiceJoinChannel with this data.
   */
  create: Prisma.XOR<Prisma.TempVoiceJoinChannelCreateInput, Prisma.TempVoiceJoinChannelUncheckedCreateInput>
  /**
   * In case the TempVoiceJoinChannel was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TempVoiceJoinChannelUpdateInput, Prisma.TempVoiceJoinChannelUncheckedUpdateInput>
}

/**
 * TempVoiceJoinChannel delete
 */
export type TempVoiceJoinChannelDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceJoinChannel
   */
  select?: Prisma.TempVoiceJoinChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceJoinChannel
   */
  omit?: Prisma.TempVoiceJoinChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceJoinChannelInclude<ExtArgs> | null
  /**
   * Filter which TempVoiceJoinChannel to delete.
   */
  where: Prisma.TempVoiceJoinChannelWhereUniqueInput
}

/**
 * TempVoiceJoinChannel deleteMany
 */
export type TempVoiceJoinChannelDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TempVoiceJoinChannels to delete
   */
  where?: Prisma.TempVoiceJoinChannelWhereInput
  /**
   * Limit how many TempVoiceJoinChannels to delete.
   */
  limit?: number
}

/**
 * TempVoiceJoinChannel without action
 */
export type TempVoiceJoinChannelDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceJoinChannel
   */
  select?: Prisma.TempVoiceJoinChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceJoinChannel
   */
  omit?: Prisma.TempVoiceJoinChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceJoinChannelInclude<ExtArgs> | null
}
