
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.js"
import { type PrismaClient } from "./class.js"

export type * from '../models.js'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.2.0
 * Query Engine version: 0c8ef2ce45c83248ab3df073180d5eda9e8be7a3
 */
export const prismaVersion: PrismaVersion = {
  client: "7.2.0",
  engine: "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Birthday: 'Birthday',
  GuildConfig: 'GuildConfig',
  TempVoiceSystem: 'TempVoiceSystem',
  TempVoiceJoinChannel: 'TempVoiceJoinChannel',
  TempVoiceTemplate: 'TempVoiceTemplate',
  TempVoiceChannel: 'TempVoiceChannel'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "birthday" | "guildConfig" | "tempVoiceSystem" | "tempVoiceJoinChannel" | "tempVoiceTemplate" | "tempVoiceChannel"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Birthday: {
      payload: Prisma.$BirthdayPayload<ExtArgs>
      fields: Prisma.BirthdayFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BirthdayFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BirthdayPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BirthdayFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BirthdayPayload>
        }
        findFirst: {
          args: Prisma.BirthdayFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BirthdayPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BirthdayFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BirthdayPayload>
        }
        findMany: {
          args: Prisma.BirthdayFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BirthdayPayload>[]
        }
        create: {
          args: Prisma.BirthdayCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BirthdayPayload>
        }
        createMany: {
          args: Prisma.BirthdayCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BirthdayCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BirthdayPayload>[]
        }
        delete: {
          args: Prisma.BirthdayDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BirthdayPayload>
        }
        update: {
          args: Prisma.BirthdayUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BirthdayPayload>
        }
        deleteMany: {
          args: Prisma.BirthdayDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BirthdayUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BirthdayUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BirthdayPayload>[]
        }
        upsert: {
          args: Prisma.BirthdayUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BirthdayPayload>
        }
        aggregate: {
          args: Prisma.BirthdayAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBirthday>
        }
        groupBy: {
          args: Prisma.BirthdayGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BirthdayGroupByOutputType>[]
        }
        count: {
          args: Prisma.BirthdayCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BirthdayCountAggregateOutputType> | number
        }
      }
    }
    GuildConfig: {
      payload: Prisma.$GuildConfigPayload<ExtArgs>
      fields: Prisma.GuildConfigFieldRefs
      operations: {
        findUnique: {
          args: Prisma.GuildConfigFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GuildConfigPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.GuildConfigFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GuildConfigPayload>
        }
        findFirst: {
          args: Prisma.GuildConfigFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GuildConfigPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.GuildConfigFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GuildConfigPayload>
        }
        findMany: {
          args: Prisma.GuildConfigFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GuildConfigPayload>[]
        }
        create: {
          args: Prisma.GuildConfigCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GuildConfigPayload>
        }
        createMany: {
          args: Prisma.GuildConfigCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.GuildConfigCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GuildConfigPayload>[]
        }
        delete: {
          args: Prisma.GuildConfigDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GuildConfigPayload>
        }
        update: {
          args: Prisma.GuildConfigUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GuildConfigPayload>
        }
        deleteMany: {
          args: Prisma.GuildConfigDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.GuildConfigUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.GuildConfigUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GuildConfigPayload>[]
        }
        upsert: {
          args: Prisma.GuildConfigUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GuildConfigPayload>
        }
        aggregate: {
          args: Prisma.GuildConfigAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateGuildConfig>
        }
        groupBy: {
          args: Prisma.GuildConfigGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GuildConfigGroupByOutputType>[]
        }
        count: {
          args: Prisma.GuildConfigCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GuildConfigCountAggregateOutputType> | number
        }
      }
    }
    TempVoiceSystem: {
      payload: Prisma.$TempVoiceSystemPayload<ExtArgs>
      fields: Prisma.TempVoiceSystemFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TempVoiceSystemFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceSystemPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TempVoiceSystemFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceSystemPayload>
        }
        findFirst: {
          args: Prisma.TempVoiceSystemFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceSystemPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TempVoiceSystemFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceSystemPayload>
        }
        findMany: {
          args: Prisma.TempVoiceSystemFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceSystemPayload>[]
        }
        create: {
          args: Prisma.TempVoiceSystemCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceSystemPayload>
        }
        createMany: {
          args: Prisma.TempVoiceSystemCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TempVoiceSystemCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceSystemPayload>[]
        }
        delete: {
          args: Prisma.TempVoiceSystemDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceSystemPayload>
        }
        update: {
          args: Prisma.TempVoiceSystemUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceSystemPayload>
        }
        deleteMany: {
          args: Prisma.TempVoiceSystemDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TempVoiceSystemUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TempVoiceSystemUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceSystemPayload>[]
        }
        upsert: {
          args: Prisma.TempVoiceSystemUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceSystemPayload>
        }
        aggregate: {
          args: Prisma.TempVoiceSystemAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTempVoiceSystem>
        }
        groupBy: {
          args: Prisma.TempVoiceSystemGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TempVoiceSystemGroupByOutputType>[]
        }
        count: {
          args: Prisma.TempVoiceSystemCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TempVoiceSystemCountAggregateOutputType> | number
        }
      }
    }
    TempVoiceJoinChannel: {
      payload: Prisma.$TempVoiceJoinChannelPayload<ExtArgs>
      fields: Prisma.TempVoiceJoinChannelFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TempVoiceJoinChannelFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceJoinChannelPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TempVoiceJoinChannelFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceJoinChannelPayload>
        }
        findFirst: {
          args: Prisma.TempVoiceJoinChannelFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceJoinChannelPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TempVoiceJoinChannelFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceJoinChannelPayload>
        }
        findMany: {
          args: Prisma.TempVoiceJoinChannelFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceJoinChannelPayload>[]
        }
        create: {
          args: Prisma.TempVoiceJoinChannelCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceJoinChannelPayload>
        }
        createMany: {
          args: Prisma.TempVoiceJoinChannelCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TempVoiceJoinChannelCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceJoinChannelPayload>[]
        }
        delete: {
          args: Prisma.TempVoiceJoinChannelDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceJoinChannelPayload>
        }
        update: {
          args: Prisma.TempVoiceJoinChannelUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceJoinChannelPayload>
        }
        deleteMany: {
          args: Prisma.TempVoiceJoinChannelDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TempVoiceJoinChannelUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TempVoiceJoinChannelUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceJoinChannelPayload>[]
        }
        upsert: {
          args: Prisma.TempVoiceJoinChannelUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceJoinChannelPayload>
        }
        aggregate: {
          args: Prisma.TempVoiceJoinChannelAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTempVoiceJoinChannel>
        }
        groupBy: {
          args: Prisma.TempVoiceJoinChannelGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TempVoiceJoinChannelGroupByOutputType>[]
        }
        count: {
          args: Prisma.TempVoiceJoinChannelCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TempVoiceJoinChannelCountAggregateOutputType> | number
        }
      }
    }
    TempVoiceTemplate: {
      payload: Prisma.$TempVoiceTemplatePayload<ExtArgs>
      fields: Prisma.TempVoiceTemplateFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TempVoiceTemplateFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceTemplatePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TempVoiceTemplateFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceTemplatePayload>
        }
        findFirst: {
          args: Prisma.TempVoiceTemplateFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceTemplatePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TempVoiceTemplateFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceTemplatePayload>
        }
        findMany: {
          args: Prisma.TempVoiceTemplateFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceTemplatePayload>[]
        }
        create: {
          args: Prisma.TempVoiceTemplateCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceTemplatePayload>
        }
        createMany: {
          args: Prisma.TempVoiceTemplateCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TempVoiceTemplateCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceTemplatePayload>[]
        }
        delete: {
          args: Prisma.TempVoiceTemplateDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceTemplatePayload>
        }
        update: {
          args: Prisma.TempVoiceTemplateUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceTemplatePayload>
        }
        deleteMany: {
          args: Prisma.TempVoiceTemplateDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TempVoiceTemplateUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TempVoiceTemplateUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceTemplatePayload>[]
        }
        upsert: {
          args: Prisma.TempVoiceTemplateUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceTemplatePayload>
        }
        aggregate: {
          args: Prisma.TempVoiceTemplateAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTempVoiceTemplate>
        }
        groupBy: {
          args: Prisma.TempVoiceTemplateGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TempVoiceTemplateGroupByOutputType>[]
        }
        count: {
          args: Prisma.TempVoiceTemplateCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TempVoiceTemplateCountAggregateOutputType> | number
        }
      }
    }
    TempVoiceChannel: {
      payload: Prisma.$TempVoiceChannelPayload<ExtArgs>
      fields: Prisma.TempVoiceChannelFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TempVoiceChannelFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceChannelPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TempVoiceChannelFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceChannelPayload>
        }
        findFirst: {
          args: Prisma.TempVoiceChannelFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceChannelPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TempVoiceChannelFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceChannelPayload>
        }
        findMany: {
          args: Prisma.TempVoiceChannelFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceChannelPayload>[]
        }
        create: {
          args: Prisma.TempVoiceChannelCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceChannelPayload>
        }
        createMany: {
          args: Prisma.TempVoiceChannelCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TempVoiceChannelCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceChannelPayload>[]
        }
        delete: {
          args: Prisma.TempVoiceChannelDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceChannelPayload>
        }
        update: {
          args: Prisma.TempVoiceChannelUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceChannelPayload>
        }
        deleteMany: {
          args: Prisma.TempVoiceChannelDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TempVoiceChannelUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TempVoiceChannelUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceChannelPayload>[]
        }
        upsert: {
          args: Prisma.TempVoiceChannelUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TempVoiceChannelPayload>
        }
        aggregate: {
          args: Prisma.TempVoiceChannelAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTempVoiceChannel>
        }
        groupBy: {
          args: Prisma.TempVoiceChannelGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TempVoiceChannelGroupByOutputType>[]
        }
        count: {
          args: Prisma.TempVoiceChannelCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TempVoiceChannelCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const BirthdayScalarFieldEnum = {
  userId: 'userId',
  day: 'day',
  month: 'month',
  year: 'year',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BirthdayScalarFieldEnum = (typeof BirthdayScalarFieldEnum)[keyof typeof BirthdayScalarFieldEnum]


export const GuildConfigScalarFieldEnum = {
  guildId: 'guildId',
  birthdayChannelId: 'birthdayChannelId',
  birthdayRoleId: 'birthdayRoleId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GuildConfigScalarFieldEnum = (typeof GuildConfigScalarFieldEnum)[keyof typeof GuildConfigScalarFieldEnum]


export const TempVoiceSystemScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  name: 'name',
  categoryId: 'categoryId',
  enabled: 'enabled',
  deleteDelay: 'deleteDelay',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TempVoiceSystemScalarFieldEnum = (typeof TempVoiceSystemScalarFieldEnum)[keyof typeof TempVoiceSystemScalarFieldEnum]


export const TempVoiceJoinChannelScalarFieldEnum = {
  id: 'id',
  channelId: 'channelId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  systemId: 'systemId'
} as const

export type TempVoiceJoinChannelScalarFieldEnum = (typeof TempVoiceJoinChannelScalarFieldEnum)[keyof typeof TempVoiceJoinChannelScalarFieldEnum]


export const TempVoiceTemplateScalarFieldEnum = {
  id: 'id',
  type: 'type',
  nameTemplate: 'nameTemplate',
  userLimit: 'userLimit',
  bitrate: 'bitrate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  systemId: 'systemId'
} as const

export type TempVoiceTemplateScalarFieldEnum = (typeof TempVoiceTemplateScalarFieldEnum)[keyof typeof TempVoiceTemplateScalarFieldEnum]


export const TempVoiceChannelScalarFieldEnum = {
  id: 'id',
  systemId: 'systemId',
  channelId: 'channelId',
  ownerId: 'ownerId',
  templateType: 'templateType',
  createdAt: 'createdAt',
  lastActiveAt: 'lastActiveAt'
} as const

export type TempVoiceChannelScalarFieldEnum = (typeof TempVoiceChannelScalarFieldEnum)[keyof typeof TempVoiceChannelScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'TempVoiceType'
 */
export type EnumTempVoiceTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'TempVoiceType'>
    


/**
 * Reference to a field of type 'TempVoiceType[]'
 */
export type ListEnumTempVoiceTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'TempVoiceType[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  birthday?: Prisma.BirthdayOmit
  guildConfig?: Prisma.GuildConfigOmit
  tempVoiceSystem?: Prisma.TempVoiceSystemOmit
  tempVoiceJoinChannel?: Prisma.TempVoiceJoinChannelOmit
  tempVoiceTemplate?: Prisma.TempVoiceTemplateOmit
  tempVoiceChannel?: Prisma.TempVoiceChannelOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

