
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Birthday: 'Birthday',
  GuildConfig: 'GuildConfig',
  TempVoiceSystem: 'TempVoiceSystem',
  TempVoiceJoinChannel: 'TempVoiceJoinChannel',
  TempVoiceTemplate: 'TempVoiceTemplate',
  TempVoiceChannel: 'TempVoiceChannel'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const BirthdayScalarFieldEnum = {
  userId: 'userId',
  day: 'day',
  month: 'month',
  year: 'year',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BirthdayScalarFieldEnum = (typeof BirthdayScalarFieldEnum)[keyof typeof BirthdayScalarFieldEnum]


export const GuildConfigScalarFieldEnum = {
  guildId: 'guildId',
  birthdayChannelId: 'birthdayChannelId',
  birthdayRoleId: 'birthdayRoleId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GuildConfigScalarFieldEnum = (typeof GuildConfigScalarFieldEnum)[keyof typeof GuildConfigScalarFieldEnum]


export const TempVoiceSystemScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  name: 'name',
  categoryId: 'categoryId',
  enabled: 'enabled',
  deleteDelay: 'deleteDelay',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TempVoiceSystemScalarFieldEnum = (typeof TempVoiceSystemScalarFieldEnum)[keyof typeof TempVoiceSystemScalarFieldEnum]


export const TempVoiceJoinChannelScalarFieldEnum = {
  id: 'id',
  channelId: 'channelId',
  templateType: 'templateType',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  systemId: 'systemId'
} as const

export type TempVoiceJoinChannelScalarFieldEnum = (typeof TempVoiceJoinChannelScalarFieldEnum)[keyof typeof TempVoiceJoinChannelScalarFieldEnum]


export const TempVoiceTemplateScalarFieldEnum = {
  id: 'id',
  type: 'type',
  nameTemplate: 'nameTemplate',
  userLimit: 'userLimit',
  bitrate: 'bitrate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  systemId: 'systemId'
} as const

export type TempVoiceTemplateScalarFieldEnum = (typeof TempVoiceTemplateScalarFieldEnum)[keyof typeof TempVoiceTemplateScalarFieldEnum]


export const TempVoiceChannelScalarFieldEnum = {
  id: 'id',
  systemId: 'systemId',
  channelId: 'channelId',
  ownerId: 'ownerId',
  templateType: 'templateType',
  createdAt: 'createdAt',
  lastActiveAt: 'lastActiveAt'
} as const

export type TempVoiceChannelScalarFieldEnum = (typeof TempVoiceChannelScalarFieldEnum)[keyof typeof TempVoiceChannelScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

